//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=4.8.3928.0.
// 

namespace CezihECDSa.Wsdl.CezihWS
{

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "CezihWsSOAP", Namespace = "urn:publicid:-:CEZIH:WS:1.0")]
    public partial class CezihWs : System.Web.Services.Protocols.SoapHttpClientProtocol
    {

        private System.Threading.SendOrPostCallback echoOperationCompleted;

        private System.Threading.SendOrPostCallback fetchListaPacijenataListOperationCompleted;

        private System.Threading.SendOrPostCallback fetchListaPacijenataZipOperationCompleted;

        private System.Threading.SendOrPostCallback fetchListaPacijenataLastZipOperationCompleted;

        private System.Threading.SendOrPostCallback uploadOperationCompleted;

        private System.Threading.SendOrPostCallback fetchListaRezultataObradeListOperationCompleted;

        private System.Threading.SendOrPostCallback fetchRezultatObradeOperationCompleted;

        private System.Threading.SendOrPostCallback arhivirajRezultatObradeOperationCompleted;

        private System.Threading.SendOrPostCallback fetchListaEKartonaListOperationCompleted;

        private System.Threading.SendOrPostCallback fetchEKartonOperationCompleted;

        private System.Threading.SendOrPostCallback arhivirajEKartonOperationCompleted;

        private System.Threading.SendOrPostCallback fetchOtisliPacijentiListOperationCompleted;

        private System.Threading.SendOrPostCallback fetchOtisliPacijentiOperationCompleted;

        private System.Threading.SendOrPostCallback arhivirajOtisliPacijentiOperationCompleted;

        private System.Threading.SendOrPostCallback fetchNeuspjesnoObradjeniRacuniOperationCompleted;

        private System.Threading.SendOrPostCallback fetchListaObavijestiListOperationCompleted;

        private System.Threading.SendOrPostCallback fetchObavijestOperationCompleted;

        /// <remarks/>
        public CezihWs()
        {
            this.Url = "https://www.cezih.hr/CezihWs/ws";
        }

        /// <remarks/>
        public event echoCompletedEventHandler echoCompleted;

        /// <remarks/>
        public event fetchListaPacijenataListCompletedEventHandler fetchListaPacijenataListCompleted;

        /// <remarks/>
        public event fetchListaPacijenataZipCompletedEventHandler fetchListaPacijenataZipCompleted;

        /// <remarks/>
        public event fetchListaPacijenataLastZipCompletedEventHandler fetchListaPacijenataLastZipCompleted;

        /// <remarks/>
        public event uploadCompletedEventHandler uploadCompleted;

        /// <remarks/>
        public event fetchListaRezultataObradeListCompletedEventHandler fetchListaRezultataObradeListCompleted;

        /// <remarks/>
        public event fetchRezultatObradeCompletedEventHandler fetchRezultatObradeCompleted;

        /// <remarks/>
        public event arhivirajRezultatObradeCompletedEventHandler arhivirajRezultatObradeCompleted;

        /// <remarks/>
        public event fetchListaEKartonaListCompletedEventHandler fetchListaEKartonaListCompleted;

        /// <remarks/>
        public event fetchEKartonCompletedEventHandler fetchEKartonCompleted;

        /// <remarks/>
        public event arhivirajEKartonCompletedEventHandler arhivirajEKartonCompleted;

        /// <remarks/>
        public event fetchOtisliPacijentiListCompletedEventHandler fetchOtisliPacijentiListCompleted;

        /// <remarks/>
        public event fetchOtisliPacijentiCompletedEventHandler fetchOtisliPacijentiCompleted;

        /// <remarks/>
        public event arhivirajOtisliPacijentiCompletedEventHandler arhivirajOtisliPacijentiCompleted;

        /// <remarks/>
        public event fetchNeuspjesnoObradjeniRacuniCompletedEventHandler fetchNeuspjesnoObradjeniRacuniCompleted;

        /// <remarks/>
        public event fetchListaObavijestiListCompletedEventHandler fetchListaObavijestiListCompleted;

        /// <remarks/>
        public event fetchObavijestCompletedEventHandler fetchObavijestCompleted;

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:publicid:-:CEZIH:WS:1.0/echo", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("EchoResponse", Namespace = "urn:publicid:-:CEZIH:WS-types:1.0")]
        public string echo([System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:publicid:-:CEZIH:WS-types:1.0")] string EchoRequest)
        {
            object[] results = this.Invoke("echo", new object[] {
                        EchoRequest});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult Beginecho(string EchoRequest, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("echo", new object[] {
                        EchoRequest}, callback, asyncState);
        }

        /// <remarks/>
        public string Endecho(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void echoAsync(string EchoRequest)
        {
            this.echoAsync(EchoRequest, null);
        }

        /// <remarks/>
        public void echoAsync(string EchoRequest, object userState)
        {
            if ((this.echoOperationCompleted == null))
            {
                this.echoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnechoOperationCompleted);
            }
            this.InvokeAsync("echo", new object[] {
                        EchoRequest}, this.echoOperationCompleted, userState);
        }

        private void OnechoOperationCompleted(object arg)
        {
            if ((this.echoCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.echoCompleted(this, new echoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:publicid:-:CEZIH:WS:1.0/fetchListaPacijenataList", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("ListaPacijenataListResponse", Namespace = "urn:publicid:-:CEZIH:WS-types:1.0")]
        public ListaPacijenataListResponse fetchListaPacijenataList([System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:publicid:-:CEZIH:WS-types:1.0")] string ListaPacijenataListRequest)
        {
            object[] results = this.Invoke("fetchListaPacijenataList", new object[] {
                        ListaPacijenataListRequest});
            return ((ListaPacijenataListResponse)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginfetchListaPacijenataList(string ListaPacijenataListRequest, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("fetchListaPacijenataList", new object[] {
                        ListaPacijenataListRequest}, callback, asyncState);
        }

        /// <remarks/>
        public ListaPacijenataListResponse EndfetchListaPacijenataList(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((ListaPacijenataListResponse)(results[0]));
        }

        /// <remarks/>
        public void fetchListaPacijenataListAsync(string ListaPacijenataListRequest)
        {
            this.fetchListaPacijenataListAsync(ListaPacijenataListRequest, null);
        }

        /// <remarks/>
        public void fetchListaPacijenataListAsync(string ListaPacijenataListRequest, object userState)
        {
            if ((this.fetchListaPacijenataListOperationCompleted == null))
            {
                this.fetchListaPacijenataListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfetchListaPacijenataListOperationCompleted);
            }
            this.InvokeAsync("fetchListaPacijenataList", new object[] {
                        ListaPacijenataListRequest}, this.fetchListaPacijenataListOperationCompleted, userState);
        }

        private void OnfetchListaPacijenataListOperationCompleted(object arg)
        {
            if ((this.fetchListaPacijenataListCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.fetchListaPacijenataListCompleted(this, new fetchListaPacijenataListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:publicid:-:CEZIH:WS:1.0/fetchListaPacijenataZip", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("ListaPacijenataZipResponse", Namespace = "urn:publicid:-:CEZIH:WS-types:1.0")]
        public ListaPacijenataZipResponse fetchListaPacijenataZip([System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:publicid:-:CEZIH:WS-types:1.0")] string ListaPacijenataZipRequest)
        {
            object[] results = this.Invoke("fetchListaPacijenataZip", new object[] {
                        ListaPacijenataZipRequest});
            return ((ListaPacijenataZipResponse)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginfetchListaPacijenataZip(string ListaPacijenataZipRequest, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("fetchListaPacijenataZip", new object[] {
                        ListaPacijenataZipRequest}, callback, asyncState);
        }

        /// <remarks/>
        public ListaPacijenataZipResponse EndfetchListaPacijenataZip(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((ListaPacijenataZipResponse)(results[0]));
        }

        /// <remarks/>
        public void fetchListaPacijenataZipAsync(string ListaPacijenataZipRequest)
        {
            this.fetchListaPacijenataZipAsync(ListaPacijenataZipRequest, null);
        }

        /// <remarks/>
        public void fetchListaPacijenataZipAsync(string ListaPacijenataZipRequest, object userState)
        {
            if ((this.fetchListaPacijenataZipOperationCompleted == null))
            {
                this.fetchListaPacijenataZipOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfetchListaPacijenataZipOperationCompleted);
            }
            this.InvokeAsync("fetchListaPacijenataZip", new object[] {
                        ListaPacijenataZipRequest}, this.fetchListaPacijenataZipOperationCompleted, userState);
        }

        private void OnfetchListaPacijenataZipOperationCompleted(object arg)
        {
            if ((this.fetchListaPacijenataZipCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.fetchListaPacijenataZipCompleted(this, new fetchListaPacijenataZipCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:publicid:-:CEZIH:WS:1.0/fetchListaPacijenataLastZip", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("ListaPacijenataLastZipResponse", Namespace = "urn:publicid:-:CEZIH:WS-types:1.0")]
        public ListaPacijenataLastZipResponse fetchListaPacijenataLastZip([System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:publicid:-:CEZIH:WS-types:1.0")] object ListaPacijenataLastZipRequest)
        {
            object[] results = this.Invoke("fetchListaPacijenataLastZip", new object[] {
                        ListaPacijenataLastZipRequest});
            return ((ListaPacijenataLastZipResponse)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginfetchListaPacijenataLastZip(object ListaPacijenataLastZipRequest, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("fetchListaPacijenataLastZip", new object[] {
                        ListaPacijenataLastZipRequest}, callback, asyncState);
        }

        /// <remarks/>
        public ListaPacijenataLastZipResponse EndfetchListaPacijenataLastZip(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((ListaPacijenataLastZipResponse)(results[0]));
        }

        /// <remarks/>
        public void fetchListaPacijenataLastZipAsync(object ListaPacijenataLastZipRequest)
        {
            this.fetchListaPacijenataLastZipAsync(ListaPacijenataLastZipRequest, null);
        }

        /// <remarks/>
        public void fetchListaPacijenataLastZipAsync(object ListaPacijenataLastZipRequest, object userState)
        {
            if ((this.fetchListaPacijenataLastZipOperationCompleted == null))
            {
                this.fetchListaPacijenataLastZipOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfetchListaPacijenataLastZipOperationCompleted);
            }
            this.InvokeAsync("fetchListaPacijenataLastZip", new object[] {
                        ListaPacijenataLastZipRequest}, this.fetchListaPacijenataLastZipOperationCompleted, userState);
        }

        private void OnfetchListaPacijenataLastZipOperationCompleted(object arg)
        {
            if ((this.fetchListaPacijenataLastZipCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.fetchListaPacijenataLastZipCompleted(this, new fetchListaPacijenataLastZipCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:publicid:-:CEZIH:WS:1.0/upload", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("UploadResponse", Namespace = "urn:publicid:-:CEZIH:WS-types:1.0")]
        public UploadResponse upload([System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:publicid:-:CEZIH:WS-types:1.0")] UploadRequest UploadRequest)
        {
            object[] results = this.Invoke("upload", new object[] {
                        UploadRequest});
            return ((UploadResponse)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult Beginupload(UploadRequest UploadRequest, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("upload", new object[] {
                        UploadRequest}, callback, asyncState);
        }

        /// <remarks/>
        public UploadResponse Endupload(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((UploadResponse)(results[0]));
        }

        /// <remarks/>
        public void uploadAsync(UploadRequest UploadRequest)
        {
            this.uploadAsync(UploadRequest, null);
        }

        /// <remarks/>
        public void uploadAsync(UploadRequest UploadRequest, object userState)
        {
            if ((this.uploadOperationCompleted == null))
            {
                this.uploadOperationCompleted = new System.Threading.SendOrPostCallback(this.OnuploadOperationCompleted);
            }
            this.InvokeAsync("upload", new object[] {
                        UploadRequest}, this.uploadOperationCompleted, userState);
        }

        private void OnuploadOperationCompleted(object arg)
        {
            if ((this.uploadCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.uploadCompleted(this, new uploadCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:publicid:-:CEZIH:WS:1.0/fetchListaRezultataObradeList", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("ListaRezultataListResponse", Namespace = "urn:publicid:-:CEZIH:WS-types:1.0")]
        public ListaRezultataListResponse fetchListaRezultataObradeList([System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:publicid:-:CEZIH:WS-types:1.0")] string ListaRezultataListRequest)
        {
            object[] results = this.Invoke("fetchListaRezultataObradeList", new object[] {
                        ListaRezultataListRequest});
            return ((ListaRezultataListResponse)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginfetchListaRezultataObradeList(string ListaRezultataListRequest, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("fetchListaRezultataObradeList", new object[] {
                        ListaRezultataListRequest}, callback, asyncState);
        }

        /// <remarks/>
        public ListaRezultataListResponse EndfetchListaRezultataObradeList(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((ListaRezultataListResponse)(results[0]));
        }

        /// <remarks/>
        public void fetchListaRezultataObradeListAsync(string ListaRezultataListRequest)
        {
            this.fetchListaRezultataObradeListAsync(ListaRezultataListRequest, null);
        }

        /// <remarks/>
        public void fetchListaRezultataObradeListAsync(string ListaRezultataListRequest, object userState)
        {
            if ((this.fetchListaRezultataObradeListOperationCompleted == null))
            {
                this.fetchListaRezultataObradeListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfetchListaRezultataObradeListOperationCompleted);
            }
            this.InvokeAsync("fetchListaRezultataObradeList", new object[] {
                        ListaRezultataListRequest}, this.fetchListaRezultataObradeListOperationCompleted, userState);
        }

        private void OnfetchListaRezultataObradeListOperationCompleted(object arg)
        {
            if ((this.fetchListaRezultataObradeListCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.fetchListaRezultataObradeListCompleted(this, new fetchListaRezultataObradeListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:publicid:-:CEZIH:WS:1.0/fetchRezultatObrade", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("RezultatObradeResponse", Namespace = "urn:publicid:-:CEZIH:WS-types:1.0")]
        public RezultatObradeResponse fetchRezultatObrade([System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:publicid:-:CEZIH:WS-types:1.0")] string RezultatObradeRequest)
        {
            object[] results = this.Invoke("fetchRezultatObrade", new object[] {
                        RezultatObradeRequest});
            return ((RezultatObradeResponse)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginfetchRezultatObrade(string RezultatObradeRequest, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("fetchRezultatObrade", new object[] {
                        RezultatObradeRequest}, callback, asyncState);
        }

        /// <remarks/>
        public RezultatObradeResponse EndfetchRezultatObrade(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((RezultatObradeResponse)(results[0]));
        }

        /// <remarks/>
        public void fetchRezultatObradeAsync(string RezultatObradeRequest)
        {
            this.fetchRezultatObradeAsync(RezultatObradeRequest, null);
        }

        /// <remarks/>
        public void fetchRezultatObradeAsync(string RezultatObradeRequest, object userState)
        {
            if ((this.fetchRezultatObradeOperationCompleted == null))
            {
                this.fetchRezultatObradeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfetchRezultatObradeOperationCompleted);
            }
            this.InvokeAsync("fetchRezultatObrade", new object[] {
                        RezultatObradeRequest}, this.fetchRezultatObradeOperationCompleted, userState);
        }

        private void OnfetchRezultatObradeOperationCompleted(object arg)
        {
            if ((this.fetchRezultatObradeCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.fetchRezultatObradeCompleted(this, new fetchRezultatObradeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:publicid:-:CEZIH:WS:1.0/arhivirajRezultatObrade", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("ArhivirajRezultatObradeResponse", Namespace = "urn:publicid:-:CEZIH:WS-types:1.0")]
        public ArhivirajRezultatObradeResponse arhivirajRezultatObrade([System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:publicid:-:CEZIH:WS-types:1.0")] string ArhivirajRezultatObradeRequest)
        {
            object[] results = this.Invoke("arhivirajRezultatObrade", new object[] {
                        ArhivirajRezultatObradeRequest});
            return ((ArhivirajRezultatObradeResponse)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginarhivirajRezultatObrade(string ArhivirajRezultatObradeRequest, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("arhivirajRezultatObrade", new object[] {
                        ArhivirajRezultatObradeRequest}, callback, asyncState);
        }

        /// <remarks/>
        public ArhivirajRezultatObradeResponse EndarhivirajRezultatObrade(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((ArhivirajRezultatObradeResponse)(results[0]));
        }

        /// <remarks/>
        public void arhivirajRezultatObradeAsync(string ArhivirajRezultatObradeRequest)
        {
            this.arhivirajRezultatObradeAsync(ArhivirajRezultatObradeRequest, null);
        }

        /// <remarks/>
        public void arhivirajRezultatObradeAsync(string ArhivirajRezultatObradeRequest, object userState)
        {
            if ((this.arhivirajRezultatObradeOperationCompleted == null))
            {
                this.arhivirajRezultatObradeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnarhivirajRezultatObradeOperationCompleted);
            }
            this.InvokeAsync("arhivirajRezultatObrade", new object[] {
                        ArhivirajRezultatObradeRequest}, this.arhivirajRezultatObradeOperationCompleted, userState);
        }

        private void OnarhivirajRezultatObradeOperationCompleted(object arg)
        {
            if ((this.arhivirajRezultatObradeCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.arhivirajRezultatObradeCompleted(this, new arhivirajRezultatObradeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:publicid:-:CEZIH:WS:1.0/fetchListaEKartonaList", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("ListaEKartonaListResponse", Namespace = "urn:publicid:-:CEZIH:WS-types:1.0")]
        public ListaEKartonaListResponse fetchListaEKartonaList([System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:publicid:-:CEZIH:WS-types:1.0")] string ListaEKartonaListRequest)
        {
            object[] results = this.Invoke("fetchListaEKartonaList", new object[] {
                        ListaEKartonaListRequest});
            return ((ListaEKartonaListResponse)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginfetchListaEKartonaList(string ListaEKartonaListRequest, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("fetchListaEKartonaList", new object[] {
                        ListaEKartonaListRequest}, callback, asyncState);
        }

        /// <remarks/>
        public ListaEKartonaListResponse EndfetchListaEKartonaList(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((ListaEKartonaListResponse)(results[0]));
        }

        /// <remarks/>
        public void fetchListaEKartonaListAsync(string ListaEKartonaListRequest)
        {
            this.fetchListaEKartonaListAsync(ListaEKartonaListRequest, null);
        }

        /// <remarks/>
        public void fetchListaEKartonaListAsync(string ListaEKartonaListRequest, object userState)
        {
            if ((this.fetchListaEKartonaListOperationCompleted == null))
            {
                this.fetchListaEKartonaListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfetchListaEKartonaListOperationCompleted);
            }
            this.InvokeAsync("fetchListaEKartonaList", new object[] {
                        ListaEKartonaListRequest}, this.fetchListaEKartonaListOperationCompleted, userState);
        }

        private void OnfetchListaEKartonaListOperationCompleted(object arg)
        {
            if ((this.fetchListaEKartonaListCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.fetchListaEKartonaListCompleted(this, new fetchListaEKartonaListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:publicid:-:CEZIH:WS:1.0/fetchEKarton", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("EKartonResponse", Namespace = "urn:publicid:-:CEZIH:WS-types:1.0")]
        public EKartonResponse fetchEKarton([System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:publicid:-:CEZIH:WS-types:1.0")] string EKartonRequest)
        {
            object[] results = this.Invoke("fetchEKarton", new object[] {
                        EKartonRequest});
            return ((EKartonResponse)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginfetchEKarton(string EKartonRequest, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("fetchEKarton", new object[] {
                        EKartonRequest}, callback, asyncState);
        }

        /// <remarks/>
        public EKartonResponse EndfetchEKarton(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((EKartonResponse)(results[0]));
        }

        /// <remarks/>
        public void fetchEKartonAsync(string EKartonRequest)
        {
            this.fetchEKartonAsync(EKartonRequest, null);
        }

        /// <remarks/>
        public void fetchEKartonAsync(string EKartonRequest, object userState)
        {
            if ((this.fetchEKartonOperationCompleted == null))
            {
                this.fetchEKartonOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfetchEKartonOperationCompleted);
            }
            this.InvokeAsync("fetchEKarton", new object[] {
                        EKartonRequest}, this.fetchEKartonOperationCompleted, userState);
        }

        private void OnfetchEKartonOperationCompleted(object arg)
        {
            if ((this.fetchEKartonCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.fetchEKartonCompleted(this, new fetchEKartonCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:publicid:-:CEZIH:WS:1.0/arhivirajEKarton", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("ArhivirajEKartonResponse", Namespace = "urn:publicid:-:CEZIH:WS-types:1.0")]
        public ArhivirajEKartonResponse arhivirajEKarton([System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:publicid:-:CEZIH:WS-types:1.0")] string ArhivirajEKartonRequest)
        {
            object[] results = this.Invoke("arhivirajEKarton", new object[] {
                        ArhivirajEKartonRequest});
            return ((ArhivirajEKartonResponse)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginarhivirajEKarton(string ArhivirajEKartonRequest, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("arhivirajEKarton", new object[] {
                        ArhivirajEKartonRequest}, callback, asyncState);
        }

        /// <remarks/>
        public ArhivirajEKartonResponse EndarhivirajEKarton(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((ArhivirajEKartonResponse)(results[0]));
        }

        /// <remarks/>
        public void arhivirajEKartonAsync(string ArhivirajEKartonRequest)
        {
            this.arhivirajEKartonAsync(ArhivirajEKartonRequest, null);
        }

        /// <remarks/>
        public void arhivirajEKartonAsync(string ArhivirajEKartonRequest, object userState)
        {
            if ((this.arhivirajEKartonOperationCompleted == null))
            {
                this.arhivirajEKartonOperationCompleted = new System.Threading.SendOrPostCallback(this.OnarhivirajEKartonOperationCompleted);
            }
            this.InvokeAsync("arhivirajEKarton", new object[] {
                        ArhivirajEKartonRequest}, this.arhivirajEKartonOperationCompleted, userState);
        }

        private void OnarhivirajEKartonOperationCompleted(object arg)
        {
            if ((this.arhivirajEKartonCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.arhivirajEKartonCompleted(this, new arhivirajEKartonCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:publicid:-:CEZIH:WS:1.0/fetchOtisliPacijentiList", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("ListaOtisliPacijentiListResponse", Namespace = "urn:publicid:-:CEZIH:WS-types:1.0")]
        public ListaOtisliPacijentiListResponse fetchOtisliPacijentiList([System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:publicid:-:CEZIH:WS-types:1.0")] string ListaOtisliPacijentiListRequest)
        {
            object[] results = this.Invoke("fetchOtisliPacijentiList", new object[] {
                        ListaOtisliPacijentiListRequest});
            return ((ListaOtisliPacijentiListResponse)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginfetchOtisliPacijentiList(string ListaOtisliPacijentiListRequest, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("fetchOtisliPacijentiList", new object[] {
                        ListaOtisliPacijentiListRequest}, callback, asyncState);
        }

        /// <remarks/>
        public ListaOtisliPacijentiListResponse EndfetchOtisliPacijentiList(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((ListaOtisliPacijentiListResponse)(results[0]));
        }

        /// <remarks/>
        public void fetchOtisliPacijentiListAsync(string ListaOtisliPacijentiListRequest)
        {
            this.fetchOtisliPacijentiListAsync(ListaOtisliPacijentiListRequest, null);
        }

        /// <remarks/>
        public void fetchOtisliPacijentiListAsync(string ListaOtisliPacijentiListRequest, object userState)
        {
            if ((this.fetchOtisliPacijentiListOperationCompleted == null))
            {
                this.fetchOtisliPacijentiListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfetchOtisliPacijentiListOperationCompleted);
            }
            this.InvokeAsync("fetchOtisliPacijentiList", new object[] {
                        ListaOtisliPacijentiListRequest}, this.fetchOtisliPacijentiListOperationCompleted, userState);
        }

        private void OnfetchOtisliPacijentiListOperationCompleted(object arg)
        {
            if ((this.fetchOtisliPacijentiListCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.fetchOtisliPacijentiListCompleted(this, new fetchOtisliPacijentiListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:publicid:-:CEZIH:WS:1.0/fetchOtisliPacijenti", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("OtisliPacijentiResponse", Namespace = "urn:publicid:-:CEZIH:WS-types:1.0")]
        public OtisliPacijentiResponse fetchOtisliPacijenti([System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:publicid:-:CEZIH:WS-types:1.0")] string OtisliPacijentiRequest)
        {
            object[] results = this.Invoke("fetchOtisliPacijenti", new object[] {
                        OtisliPacijentiRequest});
            return ((OtisliPacijentiResponse)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginfetchOtisliPacijenti(string OtisliPacijentiRequest, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("fetchOtisliPacijenti", new object[] {
                        OtisliPacijentiRequest}, callback, asyncState);
        }

        /// <remarks/>
        public OtisliPacijentiResponse EndfetchOtisliPacijenti(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((OtisliPacijentiResponse)(results[0]));
        }

        /// <remarks/>
        public void fetchOtisliPacijentiAsync(string OtisliPacijentiRequest)
        {
            this.fetchOtisliPacijentiAsync(OtisliPacijentiRequest, null);
        }

        /// <remarks/>
        public void fetchOtisliPacijentiAsync(string OtisliPacijentiRequest, object userState)
        {
            if ((this.fetchOtisliPacijentiOperationCompleted == null))
            {
                this.fetchOtisliPacijentiOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfetchOtisliPacijentiOperationCompleted);
            }
            this.InvokeAsync("fetchOtisliPacijenti", new object[] {
                        OtisliPacijentiRequest}, this.fetchOtisliPacijentiOperationCompleted, userState);
        }

        private void OnfetchOtisliPacijentiOperationCompleted(object arg)
        {
            if ((this.fetchOtisliPacijentiCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.fetchOtisliPacijentiCompleted(this, new fetchOtisliPacijentiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:publicid:-:CEZIH:WS:1.0/arhivirajOtisliPacijenti", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("ArhivirajOtisliPacijentiResponse", Namespace = "urn:publicid:-:CEZIH:WS-types:1.0")]
        public ArhivirajOtisliPacijentiResponse arhivirajOtisliPacijenti([System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:publicid:-:CEZIH:WS-types:1.0")] string ArhivirajOtisliPacijentiRequest)
        {
            object[] results = this.Invoke("arhivirajOtisliPacijenti", new object[] {
                        ArhivirajOtisliPacijentiRequest});
            return ((ArhivirajOtisliPacijentiResponse)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginarhivirajOtisliPacijenti(string ArhivirajOtisliPacijentiRequest, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("arhivirajOtisliPacijenti", new object[] {
                        ArhivirajOtisliPacijentiRequest}, callback, asyncState);
        }

        /// <remarks/>
        public ArhivirajOtisliPacijentiResponse EndarhivirajOtisliPacijenti(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((ArhivirajOtisliPacijentiResponse)(results[0]));
        }

        /// <remarks/>
        public void arhivirajOtisliPacijentiAsync(string ArhivirajOtisliPacijentiRequest)
        {
            this.arhivirajOtisliPacijentiAsync(ArhivirajOtisliPacijentiRequest, null);
        }

        /// <remarks/>
        public void arhivirajOtisliPacijentiAsync(string ArhivirajOtisliPacijentiRequest, object userState)
        {
            if ((this.arhivirajOtisliPacijentiOperationCompleted == null))
            {
                this.arhivirajOtisliPacijentiOperationCompleted = new System.Threading.SendOrPostCallback(this.OnarhivirajOtisliPacijentiOperationCompleted);
            }
            this.InvokeAsync("arhivirajOtisliPacijenti", new object[] {
                        ArhivirajOtisliPacijentiRequest}, this.arhivirajOtisliPacijentiOperationCompleted, userState);
        }

        private void OnarhivirajOtisliPacijentiOperationCompleted(object arg)
        {
            if ((this.arhivirajOtisliPacijentiCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.arhivirajOtisliPacijentiCompleted(this, new arhivirajOtisliPacijentiCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:publicid:-:CEZIH:WS:1.0/fetchNeuspjesnoObradjeniRacuni", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("NeuspjesnoObradjeniRacuniResponse", Namespace = "urn:publicid:-:CEZIH:WS-types:1.0")]
        public NeuspjesnoObradjeniRacuniResponse fetchNeuspjesnoObradjeniRacuni([System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:publicid:-:CEZIH:WS-types:1.0")] NeuspjesnoObradjeniRacuniRequest NeuspjesnoObradjeniRacuniRequest)
        {
            object[] results = this.Invoke("fetchNeuspjesnoObradjeniRacuni", new object[] {
                        NeuspjesnoObradjeniRacuniRequest});
            return ((NeuspjesnoObradjeniRacuniResponse)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginfetchNeuspjesnoObradjeniRacuni(NeuspjesnoObradjeniRacuniRequest NeuspjesnoObradjeniRacuniRequest, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("fetchNeuspjesnoObradjeniRacuni", new object[] {
                        NeuspjesnoObradjeniRacuniRequest}, callback, asyncState);
        }

        /// <remarks/>
        public NeuspjesnoObradjeniRacuniResponse EndfetchNeuspjesnoObradjeniRacuni(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((NeuspjesnoObradjeniRacuniResponse)(results[0]));
        }

        /// <remarks/>
        public void fetchNeuspjesnoObradjeniRacuniAsync(NeuspjesnoObradjeniRacuniRequest NeuspjesnoObradjeniRacuniRequest)
        {
            this.fetchNeuspjesnoObradjeniRacuniAsync(NeuspjesnoObradjeniRacuniRequest, null);
        }

        /// <remarks/>
        public void fetchNeuspjesnoObradjeniRacuniAsync(NeuspjesnoObradjeniRacuniRequest NeuspjesnoObradjeniRacuniRequest, object userState)
        {
            if ((this.fetchNeuspjesnoObradjeniRacuniOperationCompleted == null))
            {
                this.fetchNeuspjesnoObradjeniRacuniOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfetchNeuspjesnoObradjeniRacuniOperationCompleted);
            }
            this.InvokeAsync("fetchNeuspjesnoObradjeniRacuni", new object[] {
                        NeuspjesnoObradjeniRacuniRequest}, this.fetchNeuspjesnoObradjeniRacuniOperationCompleted, userState);
        }

        private void OnfetchNeuspjesnoObradjeniRacuniOperationCompleted(object arg)
        {
            if ((this.fetchNeuspjesnoObradjeniRacuniCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.fetchNeuspjesnoObradjeniRacuniCompleted(this, new fetchNeuspjesnoObradjeniRacuniCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:publicid:-:CEZIH:WS:1.0/fetchListaObavijestiList", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("ListaObavijestiListResponse", Namespace = "urn:publicid:-:CEZIH:WS-types:1.0")]
        public ListaObavijestiListResponse fetchListaObavijestiList([System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:publicid:-:CEZIH:WS-types:1.0")] string ListaObavijestiListRequest)
        {
            object[] results = this.Invoke("fetchListaObavijestiList", new object[] {
                        ListaObavijestiListRequest});
            return ((ListaObavijestiListResponse)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginfetchListaObavijestiList(string ListaObavijestiListRequest, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("fetchListaObavijestiList", new object[] {
                        ListaObavijestiListRequest}, callback, asyncState);
        }

        /// <remarks/>
        public ListaObavijestiListResponse EndfetchListaObavijestiList(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((ListaObavijestiListResponse)(results[0]));
        }

        /// <remarks/>
        public void fetchListaObavijestiListAsync(string ListaObavijestiListRequest)
        {
            this.fetchListaObavijestiListAsync(ListaObavijestiListRequest, null);
        }

        /// <remarks/>
        public void fetchListaObavijestiListAsync(string ListaObavijestiListRequest, object userState)
        {
            if ((this.fetchListaObavijestiListOperationCompleted == null))
            {
                this.fetchListaObavijestiListOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfetchListaObavijestiListOperationCompleted);
            }
            this.InvokeAsync("fetchListaObavijestiList", new object[] {
                        ListaObavijestiListRequest}, this.fetchListaObavijestiListOperationCompleted, userState);
        }

        private void OnfetchListaObavijestiListOperationCompleted(object arg)
        {
            if ((this.fetchListaObavijestiListCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.fetchListaObavijestiListCompleted(this, new fetchListaObavijestiListCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:publicid:-:CEZIH:WS:1.0/fetchObavijest", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("ObavijestResponse", Namespace = "urn:publicid:-:CEZIH:WS-types:1.0")]
        public ObavijestResponse fetchObavijest([System.Xml.Serialization.XmlElementAttribute(Namespace = "urn:publicid:-:CEZIH:WS-types:1.0")] ObavijestRequest ObavijestRequest)
        {
            object[] results = this.Invoke("fetchObavijest", new object[] {
                        ObavijestRequest});
            return ((ObavijestResponse)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginfetchObavijest(ObavijestRequest ObavijestRequest, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("fetchObavijest", new object[] {
                        ObavijestRequest}, callback, asyncState);
        }

        /// <remarks/>
        public ObavijestResponse EndfetchObavijest(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((ObavijestResponse)(results[0]));
        }

        /// <remarks/>
        public void fetchObavijestAsync(ObavijestRequest ObavijestRequest)
        {
            this.fetchObavijestAsync(ObavijestRequest, null);
        }

        /// <remarks/>
        public void fetchObavijestAsync(ObavijestRequest ObavijestRequest, object userState)
        {
            if ((this.fetchObavijestOperationCompleted == null))
            {
                this.fetchObavijestOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfetchObavijestOperationCompleted);
            }
            this.InvokeAsync("fetchObavijest", new object[] {
                        ObavijestRequest}, this.fetchObavijestOperationCompleted, userState);
        }

        private void OnfetchObavijestOperationCompleted(object arg)
        {
            if ((this.fetchObavijestCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.fetchObavijestCompleted(this, new fetchObavijestCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        public new void CancelAsync(object userState)
        {
            base.CancelAsync(userState);
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:publicid:-:CEZIH:WS-types:1.0")]
    public partial class ListaPacijenataListResponse
    {

        private string[] imeMapeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("imeMape")]
        public string[] imeMape
        {
            get
            {
                return this.imeMapeField;
            }
            set
            {
                this.imeMapeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:publicid:-:CEZIH:WS-types:1.0")]
    public partial class ListaPacijenataZipResponse
    {

        private string imeDatotekeField;

        private byte[] datotekaField;

        /// <remarks/>
        public string imeDatoteke
        {
            get
            {
                return this.imeDatotekeField;
            }
            set
            {
                this.imeDatotekeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "base64Binary")]
        public byte[] datoteka
        {
            get
            {
                return this.datotekaField;
            }
            set
            {
                this.datotekaField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:publicid:-:CEZIH:WS-types:1.0")]
    public partial class ListaPacijenataLastZipResponse
    {

        private string imeDatotekeField;

        private byte[] datotekaField;

        /// <remarks/>
        public string imeDatoteke
        {
            get
            {
                return this.imeDatotekeField;
            }
            set
            {
                this.imeDatotekeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "base64Binary")]
        public byte[] datoteka
        {
            get
            {
                return this.datotekaField;
            }
            set
            {
                this.datotekaField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:publicid:-:CEZIH:WS-types:1.0")]
    public partial class UploadRequest
    {

        private string imeDatotekeField;

        private byte[] datotekaField;

        /// <remarks/>
        public string imeDatoteke
        {
            get
            {
                return this.imeDatotekeField;
            }
            set
            {
                this.imeDatotekeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "base64Binary")]
        public byte[] datoteka
        {
            get
            {
                return this.datotekaField;
            }
            set
            {
                this.datotekaField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:publicid:-:CEZIH:WS-types:1.0")]
    public enum UploadResponse
    {

        /// <remarks/>
        SUCCESS,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:publicid:-:CEZIH:WS-types:1.0")]
    public partial class ListaRezultataListResponse
    {

        private string[] imeDatotekeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("imeDatoteke")]
        public string[] imeDatoteke
        {
            get
            {
                return this.imeDatotekeField;
            }
            set
            {
                this.imeDatotekeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:publicid:-:CEZIH:WS-types:1.0")]
    public partial class RezultatObradeResponse
    {

        private string imeDatotekeField;

        private byte[] datotekaField;

        /// <remarks/>
        public string imeDatoteke
        {
            get
            {
                return this.imeDatotekeField;
            }
            set
            {
                this.imeDatotekeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "base64Binary")]
        public byte[] datoteka
        {
            get
            {
                return this.datotekaField;
            }
            set
            {
                this.datotekaField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:publicid:-:CEZIH:WS-types:1.0")]
    public enum ArhivirajRezultatObradeResponse
    {

        /// <remarks/>
        SUCCESS,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:publicid:-:CEZIH:WS-types:1.0")]
    public partial class ListaEKartonaListResponse
    {

        private string[] imeDatotekeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("imeDatoteke")]
        public string[] imeDatoteke
        {
            get
            {
                return this.imeDatotekeField;
            }
            set
            {
                this.imeDatotekeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:publicid:-:CEZIH:WS-types:1.0")]
    public partial class EKartonResponse
    {

        private string[] imeDatotekeField;

        private byte[][] datotekaField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("imeDatoteke")]
        public string[] imeDatoteke
        {
            get
            {
                return this.imeDatotekeField;
            }
            set
            {
                this.imeDatotekeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("datoteka", DataType = "base64Binary")]
        public byte[][] datoteka
        {
            get
            {
                return this.datotekaField;
            }
            set
            {
                this.datotekaField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:publicid:-:CEZIH:WS-types:1.0")]
    public enum ArhivirajEKartonResponse
    {

        /// <remarks/>
        SUCCESS,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:publicid:-:CEZIH:WS-types:1.0")]
    public partial class ListaOtisliPacijentiListResponse
    {

        private string[] imeDatotekeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("imeDatoteke")]
        public string[] imeDatoteke
        {
            get
            {
                return this.imeDatotekeField;
            }
            set
            {
                this.imeDatotekeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:publicid:-:CEZIH:WS-types:1.0")]
    public partial class OtisliPacijentiResponse
    {

        private byte[] datotekaField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "base64Binary")]
        public byte[] datoteka
        {
            get
            {
                return this.datotekaField;
            }
            set
            {
                this.datotekaField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:publicid:-:CEZIH:WS-types:1.0")]
    public enum ArhivirajOtisliPacijentiResponse
    {

        /// <remarks/>
        SUCCESS,
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:publicid:-:CEZIH:WS-types:1.0")]
    public partial class NeuspjesnoObradjeniRacuniRequest
    {

        private System.DateTime datumOdField;

        private System.DateTime datumDoField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime datumOd
        {
            get
            {
                return this.datumOdField;
            }
            set
            {
                this.datumOdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime datumDo
        {
            get
            {
                return this.datumDoField;
            }
            set
            {
                this.datumDoField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:publicid:-:CEZIH:WS-types:1.0")]
    public partial class NeuspjesnoObradjeniRacuniResponse
    {

        private byte[] fileField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("file")]
        public byte[] file
        {
            get
            {
                return this.fileField;
            }
            set
            {
                this.fileField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:publicid:-:CEZIH:WS-types:1.0")]
    public partial class file
    {

        private string[] institutionNumberField;

        private string[] mboField;

        private string[] fileTypeField;

        private System.DateTime[] uploadDateField;

        private string[] ordinalField;

        private string[] statusField;

        private string[] statusDescriptionField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("institutionNumber")]
        public string[] institutionNumber
        {
            get
            {
                return this.institutionNumberField;
            }
            set
            {
                this.institutionNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("mbo")]
        public string[] mbo
        {
            get
            {
                return this.mboField;
            }
            set
            {
                this.mboField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("fileType")]
        public string[] fileType
        {
            get
            {
                return this.fileTypeField;
            }
            set
            {
                this.fileTypeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("uploadDate", DataType = "date")]
        public System.DateTime[] uploadDate
        {
            get
            {
                return this.uploadDateField;
            }
            set
            {
                this.uploadDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ordinal")]
        public string[] ordinal
        {
            get
            {
                return this.ordinalField;
            }
            set
            {
                this.ordinalField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("status")]
        public string[] status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("statusDescription")]
        public string[] statusDescription
        {
            get
            {
                return this.statusDescriptionField;
            }
            set
            {
                this.statusDescriptionField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:publicid:-:CEZIH:WS-types:1.0")]
    public partial class ListaObavijestiListResponse
    {

        private string[] imeDatotekeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("imeDatoteke")]
        public string[] imeDatoteke
        {
            get
            {
                return this.imeDatotekeField;
            }
            set
            {
                this.imeDatotekeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:publicid:-:CEZIH:WS-types:1.0")]
    public partial class ObavijestRequest
    {

        private string[] imeDatotekeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("imeDatoteke")]
        public string[] imeDatoteke
        {
            get
            {
                return this.imeDatotekeField;
            }
            set
            {
                this.imeDatotekeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:publicid:-:CEZIH:WS-types:1.0")]
    public partial class ObavijestResponse
    {

        private obavijestDatoteka[] obavijestDatotekaField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("obavijestDatoteka")]
        public obavijestDatoteka[] obavijestDatoteka
        {
            get
            {
                return this.obavijestDatotekaField;
            }
            set
            {
                this.obavijestDatotekaField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "urn:publicid:-:CEZIH:WS-types:1.0")]
    public partial class obavijestDatoteka
    {

        private string imeDatotekeField;

        private byte[] datotekaField;

        /// <remarks/>
        public string imeDatoteke
        {
            get
            {
                return this.imeDatotekeField;
            }
            set
            {
                this.imeDatotekeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "base64Binary")]
        public byte[] datoteka
        {
            get
            {
                return this.datotekaField;
            }
            set
            {
                this.datotekaField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    public delegate void echoCompletedEventHandler(object sender, echoCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class echoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal echoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    public delegate void fetchListaPacijenataListCompletedEventHandler(object sender, fetchListaPacijenataListCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class fetchListaPacijenataListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal fetchListaPacijenataListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public ListaPacijenataListResponse Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((ListaPacijenataListResponse)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    public delegate void fetchListaPacijenataZipCompletedEventHandler(object sender, fetchListaPacijenataZipCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class fetchListaPacijenataZipCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal fetchListaPacijenataZipCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public ListaPacijenataZipResponse Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((ListaPacijenataZipResponse)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    public delegate void fetchListaPacijenataLastZipCompletedEventHandler(object sender, fetchListaPacijenataLastZipCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class fetchListaPacijenataLastZipCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal fetchListaPacijenataLastZipCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public ListaPacijenataLastZipResponse Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((ListaPacijenataLastZipResponse)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    public delegate void uploadCompletedEventHandler(object sender, uploadCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class uploadCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal uploadCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public UploadResponse Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((UploadResponse)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    public delegate void fetchListaRezultataObradeListCompletedEventHandler(object sender, fetchListaRezultataObradeListCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class fetchListaRezultataObradeListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal fetchListaRezultataObradeListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public ListaRezultataListResponse Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((ListaRezultataListResponse)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    public delegate void fetchRezultatObradeCompletedEventHandler(object sender, fetchRezultatObradeCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class fetchRezultatObradeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal fetchRezultatObradeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public RezultatObradeResponse Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((RezultatObradeResponse)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    public delegate void arhivirajRezultatObradeCompletedEventHandler(object sender, arhivirajRezultatObradeCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class arhivirajRezultatObradeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal arhivirajRezultatObradeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public ArhivirajRezultatObradeResponse Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((ArhivirajRezultatObradeResponse)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    public delegate void fetchListaEKartonaListCompletedEventHandler(object sender, fetchListaEKartonaListCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class fetchListaEKartonaListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal fetchListaEKartonaListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public ListaEKartonaListResponse Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((ListaEKartonaListResponse)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    public delegate void fetchEKartonCompletedEventHandler(object sender, fetchEKartonCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class fetchEKartonCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal fetchEKartonCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public EKartonResponse Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((EKartonResponse)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    public delegate void arhivirajEKartonCompletedEventHandler(object sender, arhivirajEKartonCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class arhivirajEKartonCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal arhivirajEKartonCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public ArhivirajEKartonResponse Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((ArhivirajEKartonResponse)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    public delegate void fetchOtisliPacijentiListCompletedEventHandler(object sender, fetchOtisliPacijentiListCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class fetchOtisliPacijentiListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal fetchOtisliPacijentiListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public ListaOtisliPacijentiListResponse Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((ListaOtisliPacijentiListResponse)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    public delegate void fetchOtisliPacijentiCompletedEventHandler(object sender, fetchOtisliPacijentiCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class fetchOtisliPacijentiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal fetchOtisliPacijentiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public OtisliPacijentiResponse Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((OtisliPacijentiResponse)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    public delegate void arhivirajOtisliPacijentiCompletedEventHandler(object sender, arhivirajOtisliPacijentiCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class arhivirajOtisliPacijentiCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal arhivirajOtisliPacijentiCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public ArhivirajOtisliPacijentiResponse Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((ArhivirajOtisliPacijentiResponse)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    public delegate void fetchNeuspjesnoObradjeniRacuniCompletedEventHandler(object sender, fetchNeuspjesnoObradjeniRacuniCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class fetchNeuspjesnoObradjeniRacuniCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal fetchNeuspjesnoObradjeniRacuniCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public NeuspjesnoObradjeniRacuniResponse Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((NeuspjesnoObradjeniRacuniResponse)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    public delegate void fetchListaObavijestiListCompletedEventHandler(object sender, fetchListaObavijestiListCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class fetchListaObavijestiListCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal fetchListaObavijestiListCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public ListaObavijestiListResponse Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((ListaObavijestiListResponse)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    public delegate void fetchObavijestCompletedEventHandler(object sender, fetchObavijestCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class fetchObavijestCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal fetchObavijestCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public ObavijestResponse Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((ObavijestResponse)(this.results[0]));
            }
        }
    }
}