//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=4.0.30319.33440.
// 



namespace CezihECDSa.Wsdl.CijepniKartonLijecnika
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "http://www.cezdlih.hr/CEZDLIH/WebServices", ConfigurationName = "CEZDLIHWS_CijepniKartonLijecnikaSoap")]
    public interface CEZDLIHWS_CijepniKartonLijecnikaSoap
    {

        // CODEGEN: Parameter 'UpitOCijepnimKartonimaIzabranogLijecnikaResult' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action = "http://www.cezdlih.hr/CEZDLIH/WebServices/UpitOCijepnimKartonimaIzabranogLijecnik" +
            "a", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        UpitOCijepnimKartonimaIzabranogLijecnikaResponse UpitOCijepnimKartonimaIzabranogLijecnika(UpitOCijepnimKartonimaIzabranogLijecnikaRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "http://www.cezdlih.hr/CEZDLIH/WebServices/UpitOCijepnimKartonimaIzabranogLijecnik" +
            "a", ReplyAction = "*")]
        System.Threading.Tasks.Task<UpitOCijepnimKartonimaIzabranogLijecnikaResponse> UpitOCijepnimKartonimaIzabranogLijecnikaAsync(UpitOCijepnimKartonimaIzabranogLijecnikaRequest request);
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.cezdlih.hr/CEZDLIH/WebServices")]
    public partial class UpitOCijepnimKartonimaIzabranogLijecnikaUpitOCijepnimKartonimaIzabranogLijecnikaRequest
    {

        private ZaglavljeZahtjevType identifikatorZahtjevField;

        private string sifraLijecnikaField;

        private int sifraVrsteCjepivoField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 0)]
        public ZaglavljeZahtjevType identifikatorZahtjev
        {
            get
            {
                return this.identifikatorZahtjevField;
            }
            set
            {
                this.identifikatorZahtjevField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public string SifraLijecnika
        {
            get
            {
                return this.sifraLijecnikaField;
            }
            set
            {
                this.sifraLijecnikaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public int SifraVrsteCjepivo
        {
            get
            {
                return this.sifraVrsteCjepivoField;
            }
            set
            {
                this.sifraVrsteCjepivoField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cezdlih.hr/CEZDLIH/WebServices")]
    public partial class ArrayOfListaOsoba
    {

        private System.DateTime vrijemeObradeZahtjevaField;

        private ArrayOfListaOsobaOsoba[] osobaField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public System.DateTime VrijemeObradeZahtjeva
        {
            get
            {
                return this.vrijemeObradeZahtjevaField;
            }
            set
            {
                this.vrijemeObradeZahtjevaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Osoba", Order = 1)]
        public ArrayOfListaOsobaOsoba[] Osoba
        {
            get
            {
                return this.osobaField;
            }
            set
            {
                this.osobaField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.cezdlih.hr/CEZDLIH/WebServices")]
    public partial class ArrayOfListaOsobaOsoba
    {

        private ArrayOfListaOsobaOsobaOsobniPodaci osobniPodaciField;

        private ArrayOfListaOsobaOsobaCijepniKarton[] cijepniKartonField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public ArrayOfListaOsobaOsobaOsobniPodaci OsobniPodaci
        {
            get
            {
                return this.osobniPodaciField;
            }
            set
            {
                this.osobniPodaciField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CijepniKarton", Order = 1)]
        public ArrayOfListaOsobaOsobaCijepniKarton[] CijepniKarton
        {
            get
            {
                return this.cijepniKartonField;
            }
            set
            {
                this.cijepniKartonField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.cezdlih.hr/CEZDLIH/WebServices")]
    public partial class ArrayOfListaOsobaOsobaOsobniPodaci
    {

        private string mBOField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public string MBO
        {
            get
            {
                return this.mBOField;
            }
            set
            {
                this.mBOField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.cezdlih.hr/CEZDLIH/WebServices")]
    public partial class ArrayOfListaOsobaOsobaCijepniKarton
    {

        private ArrayOfListaOsobaOsobaCijepniKartonCijepljenje cijepljenjeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 0)]
        public ArrayOfListaOsobaOsobaCijepniKartonCijepljenje Cijepljenje
        {
            get
            {
                return this.cijepljenjeField;
            }
            set
            {
                this.cijepljenjeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.cezdlih.hr/CEZDLIH/WebServices")]
    public partial class ArrayOfListaOsobaOsobaCijepniKartonCijepljenje
    {

        private System.DateTime datumCijepljenjaField;

        private int sifraVrsteCjepivoField;

        private string cjepivoNazivField;

        private string dozaSlijedCijepljenjaField;

        private string halmedSifraCjepivaField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date", Order = 0)]
        public System.DateTime DatumCijepljenja
        {
            get
            {
                return this.datumCijepljenjaField;
            }
            set
            {
                this.datumCijepljenjaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public int SifraVrsteCjepivo
        {
            get
            {
                return this.sifraVrsteCjepivoField;
            }
            set
            {
                this.sifraVrsteCjepivoField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public string CjepivoNaziv
        {
            get
            {
                return this.cjepivoNazivField;
            }
            set
            {
                this.cjepivoNazivField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 3)]
        public string DozaSlijedCijepljenja
        {
            get
            {
                return this.dozaSlijedCijepljenjaField;
            }
            set
            {
                this.dozaSlijedCijepljenjaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 4)]
        public string HalmedSifraCjepiva
        {
            get
            {
                return this.halmedSifraCjepivaField;
            }
            set
            {
                this.halmedSifraCjepivaField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://www.cezdlih.hr/CEZDLIH/WebServices")]
    public partial class UpitOCijepnimKartonimaIzabranogLijecnikaResponseUpitOCijepnimKartonimaIzabranogLijecnikaResult
    {

        private ZaglavljeOdgovorType identifikatorOdgovorField;

        private ArrayOfListaOsoba listaOsobaField;

        private int statusOdgovoraField;

        private ArrayOfListaGresakaTypeGreskeGreske[] listaGresakaField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true, Order = 0)]
        public ZaglavljeOdgovorType identifikatorOdgovor
        {
            get
            {
                return this.identifikatorOdgovorField;
            }
            set
            {
                this.identifikatorOdgovorField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 1)]
        public ArrayOfListaOsoba ListaOsoba
        {
            get
            {
                return this.listaOsobaField;
            }
            set
            {
                this.listaOsobaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order = 2)]
        public int StatusOdgovora
        {
            get
            {
                return this.statusOdgovoraField;
            }
            set
            {
                this.statusOdgovoraField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order = 3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Greske", IsNullable = false)]
        public ArrayOfListaGresakaTypeGreskeGreske[] ListaGresaka
        {
            get
            {
                return this.listaGresakaField;
            }
            set
            {
                this.listaGresakaField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "UpitOCijepnimKartonimaIzabranogLijecnika", WrapperNamespace = "http://www.cezdlih.hr/CEZDLIH/WebServices", IsWrapped = true)]
    public partial class UpitOCijepnimKartonimaIzabranogLijecnikaRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "UpitOCijepnimKartonimaIzabranogLijecnikaRequest", Namespace = "http://www.cezdlih.hr/CEZDLIH/WebServices", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public UpitOCijepnimKartonimaIzabranogLijecnikaUpitOCijepnimKartonimaIzabranogLijecnikaRequest UpitOCijepnimKartonimaIzabranogLijecnikaRequest1;

        public UpitOCijepnimKartonimaIzabranogLijecnikaRequest()
        {
        }

        public UpitOCijepnimKartonimaIzabranogLijecnikaRequest(UpitOCijepnimKartonimaIzabranogLijecnikaUpitOCijepnimKartonimaIzabranogLijecnikaRequest UpitOCijepnimKartonimaIzabranogLijecnikaRequest1)
        {
            this.UpitOCijepnimKartonimaIzabranogLijecnikaRequest1 = UpitOCijepnimKartonimaIzabranogLijecnikaRequest1;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName = "UpitOCijepnimKartonimaIzabranogLijecnikaResponse", WrapperNamespace = "http://www.cezdlih.hr/CEZDLIH/WebServices", IsWrapped = true)]
    public partial class UpitOCijepnimKartonimaIzabranogLijecnikaResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://www.cezdlih.hr/CEZDLIH/WebServices", Order = 0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public UpitOCijepnimKartonimaIzabranogLijecnikaResponseUpitOCijepnimKartonimaIzabranogLijecnikaResult UpitOCijepnimKartonimaIzabranogLijecnikaResult;

        public UpitOCijepnimKartonimaIzabranogLijecnikaResponse()
        {
        }

        public UpitOCijepnimKartonimaIzabranogLijecnikaResponse(UpitOCijepnimKartonimaIzabranogLijecnikaResponseUpitOCijepnimKartonimaIzabranogLijecnikaResult UpitOCijepnimKartonimaIzabranogLijecnikaResult)
        {
            this.UpitOCijepnimKartonimaIzabranogLijecnikaResult = UpitOCijepnimKartonimaIzabranogLijecnikaResult;
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CEZDLIHWS_CijepniKartonLijecnikaSoapChannel : CEZDLIHWS_CijepniKartonLijecnikaSoap, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CEZDLIHWS_CijepniKartonLijecnikaSoapClient : System.ServiceModel.ClientBase<CEZDLIHWS_CijepniKartonLijecnikaSoap>, CEZDLIHWS_CijepniKartonLijecnikaSoap
    {

        public CEZDLIHWS_CijepniKartonLijecnikaSoapClient()
        {
        }

        public CEZDLIHWS_CijepniKartonLijecnikaSoapClient(string endpointConfigurationName) :
                base(endpointConfigurationName)
        {
        }

        public CEZDLIHWS_CijepniKartonLijecnikaSoapClient(string endpointConfigurationName, string remoteAddress) :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public CEZDLIHWS_CijepniKartonLijecnikaSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public CEZDLIHWS_CijepniKartonLijecnikaSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
                base(binding, remoteAddress)
        {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UpitOCijepnimKartonimaIzabranogLijecnikaResponse CEZDLIHWS_CijepniKartonLijecnikaSoap.UpitOCijepnimKartonimaIzabranogLijecnika(UpitOCijepnimKartonimaIzabranogLijecnikaRequest request)
        {
            return base.Channel.UpitOCijepnimKartonimaIzabranogLijecnika(request);
        }

        public UpitOCijepnimKartonimaIzabranogLijecnikaResponseUpitOCijepnimKartonimaIzabranogLijecnikaResult UpitOCijepnimKartonimaIzabranogLijecnika(UpitOCijepnimKartonimaIzabranogLijecnikaUpitOCijepnimKartonimaIzabranogLijecnikaRequest UpitOCijepnimKartonimaIzabranogLijecnikaRequest1)
        {
            UpitOCijepnimKartonimaIzabranogLijecnikaRequest inValue = new UpitOCijepnimKartonimaIzabranogLijecnikaRequest();
            inValue.UpitOCijepnimKartonimaIzabranogLijecnikaRequest1 = UpitOCijepnimKartonimaIzabranogLijecnikaRequest1;
            UpitOCijepnimKartonimaIzabranogLijecnikaResponse retVal = ((CEZDLIHWS_CijepniKartonLijecnikaSoap)(this)).UpitOCijepnimKartonimaIzabranogLijecnika(inValue);
            return retVal.UpitOCijepnimKartonimaIzabranogLijecnikaResult;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UpitOCijepnimKartonimaIzabranogLijecnikaResponse> CEZDLIHWS_CijepniKartonLijecnikaSoap.UpitOCijepnimKartonimaIzabranogLijecnikaAsync(UpitOCijepnimKartonimaIzabranogLijecnikaRequest request)
        {
            return base.Channel.UpitOCijepnimKartonimaIzabranogLijecnikaAsync(request);
        }

        public System.Threading.Tasks.Task<UpitOCijepnimKartonimaIzabranogLijecnikaResponse> UpitOCijepnimKartonimaIzabranogLijecnikaAsync(UpitOCijepnimKartonimaIzabranogLijecnikaUpitOCijepnimKartonimaIzabranogLijecnikaRequest UpitOCijepnimKartonimaIzabranogLijecnikaRequest1)
        {
            UpitOCijepnimKartonimaIzabranogLijecnikaRequest inValue = new UpitOCijepnimKartonimaIzabranogLijecnikaRequest();
            inValue.UpitOCijepnimKartonimaIzabranogLijecnikaRequest1 = UpitOCijepnimKartonimaIzabranogLijecnikaRequest1;
            return ((CEZDLIHWS_CijepniKartonLijecnikaSoap)(this)).UpitOCijepnimKartonimaIzabranogLijecnikaAsync(inValue);
        }
    }
}
