//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=4.0.30319.33440.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="CzoAcLjekarneSoap", Namespace="http://tempuri.org/")]
public partial class CzoAcLjekarne : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback ObradiUlazniRacunOperationCompleted;
    
    private System.Threading.SendOrPostCallback ObradiGrupnuFakturuOperationCompleted;
    
    private System.Threading.SendOrPostCallback ProvjeriPolicuOperationCompleted;
    
    private System.Threading.SendOrPostCallback ObradiUlazniRacunZUOperationCompleted;
    
    private System.Threading.SendOrPostCallback ObradiGrupnuFakturuZUOperationCompleted;
    
    private System.Threading.SendOrPostCallback StornoRacunaZUOperationCompleted;
    
    private System.Threading.SendOrPostCallback ProvjeriPolicuZUOperationCompleted;
    
    private System.Threading.SendOrPostCallback DohvatiPoliceOperationCompleted;
    
    /// <remarks/>
    public CzoAcLjekarne() {
        this.Url = "https://b2b.crosig.hr:4444/_czo_ac_ljekarne_/czoacljekarne.asmx";
    }
    
    /// <remarks/>
    public event ObradiUlazniRacunCompletedEventHandler ObradiUlazniRacunCompleted;
    
    /// <remarks/>
    public event ObradiGrupnuFakturuCompletedEventHandler ObradiGrupnuFakturuCompleted;
    
    /// <remarks/>
    public event ProvjeriPolicuCompletedEventHandler ProvjeriPolicuCompleted;
    
    /// <remarks/>
    public event ObradiUlazniRacunZUCompletedEventHandler ObradiUlazniRacunZUCompleted;
    
    /// <remarks/>
    public event ObradiGrupnuFakturuZUCompletedEventHandler ObradiGrupnuFakturuZUCompleted;
    
    /// <remarks/>
    public event StornoRacunaZUCompletedEventHandler StornoRacunaZUCompleted;
    
    /// <remarks/>
    public event ProvjeriPolicuZUCompletedEventHandler ProvjeriPolicuZUCompleted;
    
    /// <remarks/>
    public event DohvatiPoliceCompletedEventHandler DohvatiPoliceCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObradiUlazniRacun", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string ObradiUlazniRacun(string XmlRacun, string username, string password) {
        object[] results = this.Invoke("ObradiUlazniRacun", new object[] {
                    XmlRacun,
                    username,
                    password});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginObradiUlazniRacun(string XmlRacun, string username, string password, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("ObradiUlazniRacun", new object[] {
                    XmlRacun,
                    username,
                    password}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndObradiUlazniRacun(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void ObradiUlazniRacunAsync(string XmlRacun, string username, string password) {
        this.ObradiUlazniRacunAsync(XmlRacun, username, password, null);
    }
    
    /// <remarks/>
    public void ObradiUlazniRacunAsync(string XmlRacun, string username, string password, object userState) {
        if ((this.ObradiUlazniRacunOperationCompleted == null)) {
            this.ObradiUlazniRacunOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObradiUlazniRacunOperationCompleted);
        }
        this.InvokeAsync("ObradiUlazniRacun", new object[] {
                    XmlRacun,
                    username,
                    password}, this.ObradiUlazniRacunOperationCompleted, userState);
    }
    
    private void OnObradiUlazniRacunOperationCompleted(object arg) {
        if ((this.ObradiUlazniRacunCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.ObradiUlazniRacunCompleted(this, new ObradiUlazniRacunCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObradiGrupnuFakturu", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string ObradiGrupnuFakturu(string XmlFaktura, string username, string password) {
        object[] results = this.Invoke("ObradiGrupnuFakturu", new object[] {
                    XmlFaktura,
                    username,
                    password});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginObradiGrupnuFakturu(string XmlFaktura, string username, string password, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("ObradiGrupnuFakturu", new object[] {
                    XmlFaktura,
                    username,
                    password}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndObradiGrupnuFakturu(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void ObradiGrupnuFakturuAsync(string XmlFaktura, string username, string password) {
        this.ObradiGrupnuFakturuAsync(XmlFaktura, username, password, null);
    }
    
    /// <remarks/>
    public void ObradiGrupnuFakturuAsync(string XmlFaktura, string username, string password, object userState) {
        if ((this.ObradiGrupnuFakturuOperationCompleted == null)) {
            this.ObradiGrupnuFakturuOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObradiGrupnuFakturuOperationCompleted);
        }
        this.InvokeAsync("ObradiGrupnuFakturu", new object[] {
                    XmlFaktura,
                    username,
                    password}, this.ObradiGrupnuFakturuOperationCompleted, userState);
    }
    
    private void OnObradiGrupnuFakturuOperationCompleted(object arg) {
        if ((this.ObradiGrupnuFakturuCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.ObradiGrupnuFakturuCompleted(this, new ObradiGrupnuFakturuCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ProvjeriPolicu", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string ProvjeriPolicu(string BrojPolice) {
        object[] results = this.Invoke("ProvjeriPolicu", new object[] {
                    BrojPolice});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginProvjeriPolicu(string BrojPolice, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("ProvjeriPolicu", new object[] {
                    BrojPolice}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndProvjeriPolicu(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void ProvjeriPolicuAsync(string BrojPolice) {
        this.ProvjeriPolicuAsync(BrojPolice, null);
    }
    
    /// <remarks/>
    public void ProvjeriPolicuAsync(string BrojPolice, object userState) {
        if ((this.ProvjeriPolicuOperationCompleted == null)) {
            this.ProvjeriPolicuOperationCompleted = new System.Threading.SendOrPostCallback(this.OnProvjeriPolicuOperationCompleted);
        }
        this.InvokeAsync("ProvjeriPolicu", new object[] {
                    BrojPolice}, this.ProvjeriPolicuOperationCompleted, userState);
    }
    
    private void OnProvjeriPolicuOperationCompleted(object arg) {
        if ((this.ProvjeriPolicuCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.ProvjeriPolicuCompleted(this, new ProvjeriPolicuCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObradiUlazniRacunZU", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string ObradiUlazniRacunZU(string XmlRacun, string username, string password) {
        object[] results = this.Invoke("ObradiUlazniRacunZU", new object[] {
                    XmlRacun,
                    username,
                    password});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginObradiUlazniRacunZU(string XmlRacun, string username, string password, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("ObradiUlazniRacunZU", new object[] {
                    XmlRacun,
                    username,
                    password}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndObradiUlazniRacunZU(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void ObradiUlazniRacunZUAsync(string XmlRacun, string username, string password) {
        this.ObradiUlazniRacunZUAsync(XmlRacun, username, password, null);
    }
    
    /// <remarks/>
    public void ObradiUlazniRacunZUAsync(string XmlRacun, string username, string password, object userState) {
        if ((this.ObradiUlazniRacunZUOperationCompleted == null)) {
            this.ObradiUlazniRacunZUOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObradiUlazniRacunZUOperationCompleted);
        }
        this.InvokeAsync("ObradiUlazniRacunZU", new object[] {
                    XmlRacun,
                    username,
                    password}, this.ObradiUlazniRacunZUOperationCompleted, userState);
    }
    
    private void OnObradiUlazniRacunZUOperationCompleted(object arg) {
        if ((this.ObradiUlazniRacunZUCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.ObradiUlazniRacunZUCompleted(this, new ObradiUlazniRacunZUCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObradiGrupnuFakturuZU", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string ObradiGrupnuFakturuZU(string XmlFaktura, string username, string password) {
        object[] results = this.Invoke("ObradiGrupnuFakturuZU", new object[] {
                    XmlFaktura,
                    username,
                    password});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginObradiGrupnuFakturuZU(string XmlFaktura, string username, string password, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("ObradiGrupnuFakturuZU", new object[] {
                    XmlFaktura,
                    username,
                    password}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndObradiGrupnuFakturuZU(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void ObradiGrupnuFakturuZUAsync(string XmlFaktura, string username, string password) {
        this.ObradiGrupnuFakturuZUAsync(XmlFaktura, username, password, null);
    }
    
    /// <remarks/>
    public void ObradiGrupnuFakturuZUAsync(string XmlFaktura, string username, string password, object userState) {
        if ((this.ObradiGrupnuFakturuZUOperationCompleted == null)) {
            this.ObradiGrupnuFakturuZUOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObradiGrupnuFakturuZUOperationCompleted);
        }
        this.InvokeAsync("ObradiGrupnuFakturuZU", new object[] {
                    XmlFaktura,
                    username,
                    password}, this.ObradiGrupnuFakturuZUOperationCompleted, userState);
    }
    
    private void OnObradiGrupnuFakturuZUOperationCompleted(object arg) {
        if ((this.ObradiGrupnuFakturuZUCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.ObradiGrupnuFakturuZUCompleted(this, new ObradiGrupnuFakturuZUCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/StornoRacunaZU", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string StornoRacunaZU(string XmlStorno, string username, string password) {
        object[] results = this.Invoke("StornoRacunaZU", new object[] {
                    XmlStorno,
                    username,
                    password});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginStornoRacunaZU(string XmlStorno, string username, string password, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("StornoRacunaZU", new object[] {
                    XmlStorno,
                    username,
                    password}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndStornoRacunaZU(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void StornoRacunaZUAsync(string XmlStorno, string username, string password) {
        this.StornoRacunaZUAsync(XmlStorno, username, password, null);
    }
    
    /// <remarks/>
    public void StornoRacunaZUAsync(string XmlStorno, string username, string password, object userState) {
        if ((this.StornoRacunaZUOperationCompleted == null)) {
            this.StornoRacunaZUOperationCompleted = new System.Threading.SendOrPostCallback(this.OnStornoRacunaZUOperationCompleted);
        }
        this.InvokeAsync("StornoRacunaZU", new object[] {
                    XmlStorno,
                    username,
                    password}, this.StornoRacunaZUOperationCompleted, userState);
    }
    
    private void OnStornoRacunaZUOperationCompleted(object arg) {
        if ((this.StornoRacunaZUCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.StornoRacunaZUCompleted(this, new StornoRacunaZUCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ProvjeriPolicuZU", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string ProvjeriPolicuZU(string BrojPolice, System.DateTime StartDate, string username, string password) {
        object[] results = this.Invoke("ProvjeriPolicuZU", new object[] {
                    BrojPolice,
                    StartDate,
                    username,
                    password});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginProvjeriPolicuZU(string BrojPolice, System.DateTime StartDate, string username, string password, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("ProvjeriPolicuZU", new object[] {
                    BrojPolice,
                    StartDate,
                    username,
                    password}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndProvjeriPolicuZU(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void ProvjeriPolicuZUAsync(string BrojPolice, System.DateTime StartDate, string username, string password) {
        this.ProvjeriPolicuZUAsync(BrojPolice, StartDate, username, password, null);
    }
    
    /// <remarks/>
    public void ProvjeriPolicuZUAsync(string BrojPolice, System.DateTime StartDate, string username, string password, object userState) {
        if ((this.ProvjeriPolicuZUOperationCompleted == null)) {
            this.ProvjeriPolicuZUOperationCompleted = new System.Threading.SendOrPostCallback(this.OnProvjeriPolicuZUOperationCompleted);
        }
        this.InvokeAsync("ProvjeriPolicuZU", new object[] {
                    BrojPolice,
                    StartDate,
                    username,
                    password}, this.ProvjeriPolicuZUOperationCompleted, userState);
    }
    
    private void OnProvjeriPolicuZUOperationCompleted(object arg) {
        if ((this.ProvjeriPolicuZUCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.ProvjeriPolicuZUCompleted(this, new ProvjeriPolicuZUCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/DohvatiPolice", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    public string DohvatiPolice(string Identifikator, System.DateTime StartDate, string username, string password) {
        object[] results = this.Invoke("DohvatiPolice", new object[] {
                    Identifikator,
                    StartDate,
                    username,
                    password});
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult BeginDohvatiPolice(string Identifikator, System.DateTime StartDate, string username, string password, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("DohvatiPolice", new object[] {
                    Identifikator,
                    StartDate,
                    username,
                    password}, callback, asyncState);
    }
    
    /// <remarks/>
    public string EndDohvatiPolice(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((string)(results[0]));
    }
    
    /// <remarks/>
    public void DohvatiPoliceAsync(string Identifikator, System.DateTime StartDate, string username, string password) {
        this.DohvatiPoliceAsync(Identifikator, StartDate, username, password, null);
    }
    
    /// <remarks/>
    public void DohvatiPoliceAsync(string Identifikator, System.DateTime StartDate, string username, string password, object userState) {
        if ((this.DohvatiPoliceOperationCompleted == null)) {
            this.DohvatiPoliceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDohvatiPoliceOperationCompleted);
        }
        this.InvokeAsync("DohvatiPolice", new object[] {
                    Identifikator,
                    StartDate,
                    username,
                    password}, this.DohvatiPoliceOperationCompleted, userState);
    }
    
    private void OnDohvatiPoliceOperationCompleted(object arg) {
        if ((this.DohvatiPoliceCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.DohvatiPoliceCompleted(this, new DohvatiPoliceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
public delegate void ObradiUlazniRacunCompletedEventHandler(object sender, ObradiUlazniRacunCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class ObradiUlazniRacunCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal ObradiUlazniRacunCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
public delegate void ObradiGrupnuFakturuCompletedEventHandler(object sender, ObradiGrupnuFakturuCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class ObradiGrupnuFakturuCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal ObradiGrupnuFakturuCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
public delegate void ProvjeriPolicuCompletedEventHandler(object sender, ProvjeriPolicuCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class ProvjeriPolicuCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal ProvjeriPolicuCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
public delegate void ObradiUlazniRacunZUCompletedEventHandler(object sender, ObradiUlazniRacunZUCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class ObradiUlazniRacunZUCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal ObradiUlazniRacunZUCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
public delegate void ObradiGrupnuFakturuZUCompletedEventHandler(object sender, ObradiGrupnuFakturuZUCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class ObradiGrupnuFakturuZUCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal ObradiGrupnuFakturuZUCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
public delegate void StornoRacunaZUCompletedEventHandler(object sender, StornoRacunaZUCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class StornoRacunaZUCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal StornoRacunaZUCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
public delegate void ProvjeriPolicuZUCompletedEventHandler(object sender, ProvjeriPolicuZUCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class ProvjeriPolicuZUCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal ProvjeriPolicuZUCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
public delegate void DohvatiPoliceCompletedEventHandler(object sender, DohvatiPoliceCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.0.30319.33440")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class DohvatiPoliceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal DohvatiPoliceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public string Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}
