//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CezihECDSa.Wsdl.DohvatSmjernica
{


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName = "DohvatSmjernica.DohvatSmjernicaSoap")]
    public interface DohvatSmjernicaSoap
    {

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/DohvatiSmjernice", ReplyAction = "*")]
        System.Threading.Tasks.Task<DohvatSmjernica.DohvatiSmjerniceResponse> DohvatiSmjerniceAsync(DohvatSmjernica.DohvatiSmjerniceRequest request);
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class DohvatiSmjerniceRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "DohvatiSmjernice", Namespace = "http://tempuri.org/", Order = 0)]
        public DohvatSmjernica.DohvatiSmjerniceRequestBody Body;

        public DohvatiSmjerniceRequest()
        {
        }

        public DohvatiSmjerniceRequest(DohvatSmjernica.DohvatiSmjerniceRequestBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "http://tempuri.org/")]
    public partial class DohvatiSmjerniceRequestBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public string poruka;

        public DohvatiSmjerniceRequestBody()
        {
        }

        public DohvatiSmjerniceRequestBody(string poruka)
        {
            this.poruka = poruka;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class DohvatiSmjerniceResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "DohvatiSmjerniceResponse", Namespace = "http://tempuri.org/", Order = 0)]
        public DohvatSmjernica.DohvatiSmjerniceResponseBody Body;

        public DohvatiSmjerniceResponse()
        {
        }

        public DohvatiSmjerniceResponse(DohvatSmjernica.DohvatiSmjerniceResponseBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "http://tempuri.org/")]
    public partial class DohvatiSmjerniceResponseBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public string DohvatiSmjerniceResult;

        public DohvatiSmjerniceResponseBody()
        {
        }

        public DohvatiSmjerniceResponseBody(string DohvatiSmjerniceResult)
        {
            this.DohvatiSmjerniceResult = DohvatiSmjerniceResult;
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface DohvatSmjernicaSoapChannel : DohvatSmjernica.DohvatSmjernicaSoap, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class DohvatSmjernicaSoapClient : System.ServiceModel.ClientBase<DohvatSmjernica.DohvatSmjernicaSoap>, DohvatSmjernica.DohvatSmjernicaSoap
    {

        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);

        public DohvatSmjernicaSoapClient(EndpointConfiguration endpointConfiguration) :
                base(DohvatSmjernicaSoapClient.GetBindingForEndpoint(endpointConfiguration), DohvatSmjernicaSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public DohvatSmjernicaSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) :
                base(DohvatSmjernicaSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public DohvatSmjernicaSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) :
                base(DohvatSmjernicaSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public DohvatSmjernicaSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
                base(binding, remoteAddress)
        {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DohvatSmjernica.DohvatiSmjerniceResponse> DohvatSmjernica.DohvatSmjernicaSoap.DohvatiSmjerniceAsync(DohvatSmjernica.DohvatiSmjerniceRequest request)
        {
            return base.Channel.DohvatiSmjerniceAsync(request);
        }

        public System.Threading.Tasks.Task<DohvatSmjernica.DohvatiSmjerniceResponse> DohvatiSmjerniceAsync(string poruka)
        {
            DohvatSmjernica.DohvatiSmjerniceRequest inValue = new DohvatSmjernica.DohvatiSmjerniceRequest();
            inValue.Body = new DohvatSmjernica.DohvatiSmjerniceRequestBody();
            inValue.Body.poruka = poruka;
            return ((DohvatSmjernica.DohvatSmjernicaSoap)(this)).DohvatiSmjerniceAsync(inValue);
        }

        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }

        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.DohvatSmjernicaSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.DohvatSmjernicaSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }

        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.DohvatSmjernicaSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://cezeltest.cezih.hr:32867/DohvatSmjernica.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.DohvatSmjernicaSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://cezeltest.cezih.hr:32867/DohvatSmjernica.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }

        public enum EndpointConfiguration
        {

            DohvatSmjernicaSoap,

            DohvatSmjernicaSoap12,
        }
    }
}
