//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=4.8.3928.0.
// 


/// <remarks/>
// CODEGEN: The optional WSDL extension element 'PolicyReference' from namespace 'http://schemas.xmlsoap.org/ws/2004/09/policy' was not handled.
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name = "BasicHttpBinding_IEvidencije", Namespace = "https://servis.hzzo.hr/cezih/evidencije")]
public partial class Evidencije : System.Web.Services.Protocols.SoapHttpClientProtocol
{

    private System.Threading.SendOrPostCallback PrijedlogZaProvjeruVozacaOperationCompleted;

    /// <remarks/>
    public Evidencije()
    {
        this.Url = "https://hzzo-infoothers-test.gov.hr/cezih/Evidencije.svc";
    }

    /// <remarks/>
    public event PrijedlogZaProvjeruVozacaCompletedEventHandler PrijedlogZaProvjeruVozacaCompleted;

    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://servis.hzzo.hr/cezih/evidencije/IEvidencije/PrijedlogZaProvjeruVozaca", RequestNamespace = "https://servis.hzzo.hr/cezih/evidencije", ResponseNamespace = "https://servis.hzzo.hr/cezih/evidencije", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public ZahtjevOdgovor PrijedlogZaProvjeruVozaca([System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string Oib, [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string SifraOrdinacije)
    {
        object[] results = this.Invoke("PrijedlogZaProvjeruVozaca", new object[] {
                    Oib,
                    SifraOrdinacije});
        return ((ZahtjevOdgovor)(results[0]));
    }

    /// <remarks/>
    public System.IAsyncResult BeginPrijedlogZaProvjeruVozaca(string Oib, string SifraOrdinacije, System.AsyncCallback callback, object asyncState)
    {
        return this.BeginInvoke("PrijedlogZaProvjeruVozaca", new object[] {
                    Oib,
                    SifraOrdinacije}, callback, asyncState);
    }

    /// <remarks/>
    public ZahtjevOdgovor EndPrijedlogZaProvjeruVozaca(System.IAsyncResult asyncResult)
    {
        object[] results = this.EndInvoke(asyncResult);
        return ((ZahtjevOdgovor)(results[0]));
    }

    /// <remarks/>
    public void PrijedlogZaProvjeruVozacaAsync(string Oib, string SifraOrdinacije)
    {
        this.PrijedlogZaProvjeruVozacaAsync(Oib, SifraOrdinacije, null);
    }

    /// <remarks/>
    public void PrijedlogZaProvjeruVozacaAsync(string Oib, string SifraOrdinacije, object userState)
    {
        if ((this.PrijedlogZaProvjeruVozacaOperationCompleted == null))
        {
            this.PrijedlogZaProvjeruVozacaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPrijedlogZaProvjeruVozacaOperationCompleted);
        }
        this.InvokeAsync("PrijedlogZaProvjeruVozaca", new object[] {
                    Oib,
                    SifraOrdinacije}, this.PrijedlogZaProvjeruVozacaOperationCompleted, userState);
    }

    private void OnPrijedlogZaProvjeruVozacaOperationCompleted(object arg)
    {
        if ((this.PrijedlogZaProvjeruVozacaCompleted != null))
        {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.PrijedlogZaProvjeruVozacaCompleted(this, new PrijedlogZaProvjeruVozacaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }

    /// <remarks/>
    public new void CancelAsync(object userState)
    {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.datacontract.org/2004/07/Hz.Hzzo.Ws.Cezih")]
public partial class ZahtjevOdgovor
{

    private string porukaField;

    private int statusField;

    private bool statusFieldSpecified;

    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
    public string Poruka
    {
        get
        {
            return this.porukaField;
        }
        set
        {
            this.porukaField = value;
        }
    }

    /// <remarks/>
    public int Status
    {
        get
        {
            return this.statusField;
        }
        set
        {
            this.statusField = value;
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool StatusSpecified
    {
        get
        {
            return this.statusFieldSpecified;
        }
        set
        {
            this.statusFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
public delegate void PrijedlogZaProvjeruVozacaCompletedEventHandler(object sender, PrijedlogZaProvjeruVozacaCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class PrijedlogZaProvjeruVozacaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{

    private object[] results;

    internal PrijedlogZaProvjeruVozacaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
    {
        this.results = results;
    }

    /// <remarks/>
    public ZahtjevOdgovor Result
    {
        get
        {
            this.RaiseExceptionIfNecessary();
            return ((ZahtjevOdgovor)(this.results[0]));
        }
    }
}
