//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRVozaci
{


    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.cezih.hr/HrVozacke/Incoming", ConfigurationName="HRVozaci.RezultatiPortType")]
    public interface RezultatiPortType
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cezih.hr/HrVozacke/Outgoing/SlanjeRezultata", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        HRVozaci.SlanjeRezultataResponse SlanjeRezultata(HRVozaci.SlanjeRezultataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.cezih.hr/HrVozacke/Outgoing/SlanjeRezultata", ReplyAction="*")]
        System.Threading.Tasks.Task<HRVozaci.SlanjeRezultataResponse> SlanjeRezultataAsync(HRVozaci.SlanjeRezultataRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.cezih.hr/HrVozacke/Incoming")]
    public partial class PrijavaRezultata
    {
        
        private Grp_Poruka porukaField;
        
        private Grp_Autor autorField;
        
        private string brojUvjerenjaField;
        
        private Grp_TijeloIzdavanja tijeloIzdavanjaField;
        
        private System.DateTime datumField;
        
        private string svrhaField;
        
        private Grp_Nositelj nositeljField;
        
        private Grp_Sposoban sposobanField;
        
        private Grp_Kategorije[] kategorijeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Grp_Poruka Poruka
        {
            get
            {
                return this.porukaField;
            }
            set
            {
                this.porukaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Grp_Autor Autor
        {
            get
            {
                return this.autorField;
            }
            set
            {
                this.autorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string BrojUvjerenja
        {
            get
            {
                return this.brojUvjerenjaField;
            }
            set
            {
                this.brojUvjerenjaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public Grp_TijeloIzdavanja TijeloIzdavanja
        {
            get
            {
                return this.tijeloIzdavanjaField;
            }
            set
            {
                this.tijeloIzdavanjaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=4)]
        public System.DateTime Datum
        {
            get
            {
                return this.datumField;
            }
            set
            {
                this.datumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Svrha
        {
            get
            {
                return this.svrhaField;
            }
            set
            {
                this.svrhaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public Grp_Nositelj Nositelj
        {
            get
            {
                return this.nositeljField;
            }
            set
            {
                this.nositeljField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public Grp_Sposoban Sposoban
        {
            get
            {
                return this.sposobanField;
            }
            set
            {
                this.sposobanField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Kategorije", Order=8)]
        public Grp_Kategorije[] Kategorije
        {
            get
            {
                return this.kategorijeField;
            }
            set
            {
                this.kategorijeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cezih.hr/HrVozacke/Incoming")]
    public partial class Grp_Poruka
    {
        
        private string porukaIDField;
        
        private System.DateTime vrijemeSlanjaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string PorukaID
        {
            get
            {
                return this.porukaIDField;
            }
            set
            {
                this.porukaIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime VrijemeSlanja
        {
            get
            {
                return this.vrijemeSlanjaField;
            }
            set
            {
                this.vrijemeSlanjaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cezih.hr/HrVozacke/Incoming")]
    public partial class Grp_Ogranicenje
    {
        
        private KodOgranicenja kodOgranicenjaField;
        
        private string varijablaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public KodOgranicenja KodOgranicenja
        {
            get
            {
                return this.kodOgranicenjaField;
            }
            set
            {
                this.kodOgranicenjaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Varijabla
        {
            get
            {
                return this.varijablaField;
            }
            set
            {
                this.varijablaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cezih.hr/HrVozacke/Incoming")]
    public enum KodOgranicenja
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("79")]
        Item79,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("79.01")]
        Item7901,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("79.02")]
        Item7902,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("79.03")]
        Item7903,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("79.04")]
        Item7904,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("79.05")]
        Item7905,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("79.06")]
        Item7906,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("80")]
        Item80,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("81")]
        Item81,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("96")]
        Item96,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("97")]
        Item97,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("01.07")]
        Item0107,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("31")]
        Item31,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("31.01")]
        Item3101,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("31.02")]
        Item3102,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("31.03")]
        Item3103,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("31.04")]
        Item3104,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("32")]
        Item32,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("32.01")]
        Item3201,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("32.02")]
        Item3202,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("33")]
        Item33,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("33.01")]
        Item3301,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("33.02")]
        Item3302,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("40.14")]
        Item4014,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("40.15")]
        Item4015,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("44.11")]
        Item4411,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("44.12")]
        Item4412,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("47")]
        Item47,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("61")]
        Item61,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("63")]
        Item63,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("65")]
        Item65,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("66")]
        Item66,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("67")]
        Item67,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("68")]
        Item68,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("01")]
        Item01,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("01.01")]
        Item0101,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("01.02")]
        Item0102,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("01.05")]
        Item0105,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("01.06")]
        Item0106,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("02")]
        Item02,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("03")]
        Item03,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("03.01")]
        Item0301,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("03.02")]
        Item0302,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("10")]
        Item10,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("10.02")]
        Item1002,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("10.04")]
        Item1004,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("15")]
        Item15,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("15.01")]
        Item1501,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("15.02")]
        Item1502,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("15.03")]
        Item1503,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("15.04")]
        Item1504,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("20")]
        Item20,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("20.01")]
        Item2001,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("20.03")]
        Item2003,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("20.04")]
        Item2004,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("20.05")]
        Item2005,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("20.06")]
        Item2006,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("20.09")]
        Item2009,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("20.12")]
        Item2012,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("20.13")]
        Item2013,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("20.14")]
        Item2014,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("25")]
        Item25,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("25.01")]
        Item2501,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("25.03")]
        Item2503,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("25.04")]
        Item2504,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("25.05")]
        Item2505,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("25.06")]
        Item2506,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("25.08")]
        Item2508,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("25.09")]
        Item2509,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("35")]
        Item35,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("35.02")]
        Item3502,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("35.03")]
        Item3503,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("35.04")]
        Item3504,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("35.05")]
        Item3505,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("40")]
        Item40,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("40.05")]
        Item4005,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("40.06")]
        Item4006,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("40.09")]
        Item4009,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("40.11")]
        Item4011,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("42")]
        Item42,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("42.01")]
        Item4201,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("42.03")]
        Item4203,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("42.05")]
        Item4205,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("43")]
        Item43,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("43.01")]
        Item4301,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("43.02")]
        Item4302,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("43.03")]
        Item4303,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("43.04")]
        Item4304,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("43.06")]
        Item4306,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("43.07")]
        Item4307,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("44.01")]
        Item4401,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("44.02")]
        Item4402,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("44.03")]
        Item4403,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("44.04")]
        Item4404,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("44.08")]
        Item4408,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("45")]
        Item45,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("46")]
        Item46,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("78")]
        Item78,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("102.01")]
        Item10201,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("102.02")]
        Item10202,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("73")]
        Item73,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("95.01")]
        Item9501,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("99.01")]
        Item9901,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("20.07")]
        Item2007,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("69")]
        Item69,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("50")]
        Item50,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("70")]
        Item70,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("71")]
        Item71,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("40.01")]
        Item4001,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("64")]
        Item64,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("62")]
        Item62,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("44.09")]
        Item4409,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("44.10")]
        Item4410,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("101.02")]
        Item10102,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("101.03")]
        Item10103,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("101.04")]
        Item10104,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("101.01")]
        Item10101,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("100")]
        Item100,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("95")]
        Item95,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cezih.hr/HrVozacke/Incoming")]
    public partial class Grp_Kategorije
    {
        
        private Oznaka oznakaField;
        
        private Grp_Ogranicenje[] ogranicenjeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Oznaka Oznaka
        {
            get
            {
                return this.oznakaField;
            }
            set
            {
                this.oznakaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Ogranicenje", Order=1)]
        public Grp_Ogranicenje[] Ogranicenje
        {
            get
            {
                return this.ogranicenjeField;
            }
            set
            {
                this.ogranicenjeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cezih.hr/HrVozacke/Incoming")]
    public enum Oznaka
    {
        
        /// <remarks/>
        AM,
        
        /// <remarks/>
        A1,
        
        /// <remarks/>
        A2,
        
        /// <remarks/>
        A,
        
        /// <remarks/>
        B1,
        
        /// <remarks/>
        B,
        
        /// <remarks/>
        C1,
        
        /// <remarks/>
        C,
        
        /// <remarks/>
        D1,
        
        /// <remarks/>
        D,
        
        /// <remarks/>
        BE,
        
        /// <remarks/>
        C1E,
        
        /// <remarks/>
        CE,
        
        /// <remarks/>
        D1E,
        
        /// <remarks/>
        DE,
        
        /// <remarks/>
        F,
        
        /// <remarks/>
        G,
        
        /// <remarks/>
        H,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cezih.hr/HrVozacke/Incoming")]
    public partial class Grp_Sposoban
    {
        
        private StatusSposobnosti statusSposobnostiField;
        
        private string trajanjeOgranicenjaField;
        
        private JedinicaOgranicenja jedinicaOgranicenjaField;
        
        private bool jedinicaOgranicenjaFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public StatusSposobnosti StatusSposobnosti
        {
            get
            {
                return this.statusSposobnostiField;
            }
            set
            {
                this.statusSposobnostiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=1)]
        public string TrajanjeOgranicenja
        {
            get
            {
                return this.trajanjeOgranicenjaField;
            }
            set
            {
                this.trajanjeOgranicenjaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public JedinicaOgranicenja JedinicaOgranicenja
        {
            get
            {
                return this.jedinicaOgranicenjaField;
            }
            set
            {
                this.jedinicaOgranicenjaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool JedinicaOgranicenjaSpecified
        {
            get
            {
                return this.jedinicaOgranicenjaFieldSpecified;
            }
            set
            {
                this.jedinicaOgranicenjaFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cezih.hr/HrVozacke/Incoming")]
    public enum StatusSposobnosti
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("3")]
        Item3,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("4")]
        Item4,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cezih.hr/HrVozacke/Incoming")]
    public enum JedinicaOgranicenja
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cezih.hr/HrVozacke/Incoming")]
    public partial class Grp_Nositelj
    {
        
        private string oIBField;
        
        private string mBOField;
        
        private string imeField;
        
        private string prezimeField;
        
        private string imeOcaMajkeField;
        
        private System.DateTime datumRodjenjaField;
        
        private bool datumRodjenjaFieldSpecified;
        
        private string zanimanjeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string OIB
        {
            get
            {
                return this.oIBField;
            }
            set
            {
                this.oIBField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string MBO
        {
            get
            {
                return this.mBOField;
            }
            set
            {
                this.mBOField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Ime
        {
            get
            {
                return this.imeField;
            }
            set
            {
                this.imeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Prezime
        {
            get
            {
                return this.prezimeField;
            }
            set
            {
                this.prezimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ImeOcaMajke
        {
            get
            {
                return this.imeOcaMajkeField;
            }
            set
            {
                this.imeOcaMajkeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=5)]
        public System.DateTime DatumRodjenja
        {
            get
            {
                return this.datumRodjenjaField;
            }
            set
            {
                this.datumRodjenjaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DatumRodjenjaSpecified
        {
            get
            {
                return this.datumRodjenjaFieldSpecified;
            }
            set
            {
                this.datumRodjenjaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Zanimanje
        {
            get
            {
                return this.zanimanjeField;
            }
            set
            {
                this.zanimanjeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cezih.hr/HrVozacke/Incoming")]
    public partial class Grp_TijeloIzdavanja
    {
        
        private string nazivTijelaField;
        
        private VrstaTijela vrstaTijelaField;
        
        private string oIBField;
        
        private StupanjKomisije stupanjKomisijeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string NazivTijela
        {
            get
            {
                return this.nazivTijelaField;
            }
            set
            {
                this.nazivTijelaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public VrstaTijela VrstaTijela
        {
            get
            {
                return this.vrstaTijelaField;
            }
            set
            {
                this.vrstaTijelaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string OIB
        {
            get
            {
                return this.oIBField;
            }
            set
            {
                this.oIBField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public StupanjKomisije StupanjKomisije
        {
            get
            {
                return this.stupanjKomisijeField;
            }
            set
            {
                this.stupanjKomisijeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cezih.hr/HrVozacke/Incoming")]
    public enum VrstaTijela
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cezih.hr/HrVozacke/Incoming")]
    public enum StupanjKomisije
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("2")]
        Item2,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cezih.hr/HrVozacke/Incoming")]
    public partial class Grp_AutorOrganizacija
    {
        
        private string nazivField;
        
        private string hZZOSifraField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Naziv
        {
            get
            {
                return this.nazivField;
            }
            set
            {
                this.nazivField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string HZZOSifra
        {
            get
            {
                return this.hZZOSifraField;
            }
            set
            {
                this.hZZOSifraField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cezih.hr/HrVozacke/Incoming")]
    public partial class Grp_AutorOsoba
    {
        
        private string oIBField;
        
        private string hZJZSifraField;
        
        private string imeField;
        
        private string prezimeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string OIB
        {
            get
            {
                return this.oIBField;
            }
            set
            {
                this.oIBField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string HZJZSifra
        {
            get
            {
                return this.hZJZSifraField;
            }
            set
            {
                this.hZJZSifraField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Ime
        {
            get
            {
                return this.imeField;
            }
            set
            {
                this.imeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Prezime
        {
            get
            {
                return this.prezimeField;
            }
            set
            {
                this.prezimeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cezih.hr/HrVozacke/Incoming")]
    public partial class Grp_Autor
    {
        
        private Grp_AutorOsoba autorOsobaField;
        
        private Grp_AutorOrganizacija autorOrganizacijaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Grp_AutorOsoba AutorOsoba
        {
            get
            {
                return this.autorOsobaField;
            }
            set
            {
                this.autorOsobaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public Grp_AutorOrganizacija AutorOrganizacija
        {
            get
            {
                return this.autorOrganizacijaField;
            }
            set
            {
                this.autorOrganizacijaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.cezih.hr/HrVozacke/Incoming")]
    public partial class PrijavaRezultataOdgovor
    {
        
        private Odgovor odgovorField;
        
        private Grp_GreskeGreska[] greskeField;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Odgovor Odgovor
        {
            get
            {
                return this.odgovorField;
            }
            set
            {
                this.odgovorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Greska", IsNullable=false)]
        public Grp_GreskeGreska[] Greske
        {
            get
            {
                return this.greskeField;
            }
            set
            {
                this.greskeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.cezih.hr/HrVozacke/Incoming")]
    public enum Odgovor
    {
        
        /// <remarks/>
        OK,
        
        /// <remarks/>
        NOK,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://www.cezih.hr/HrVozacke/Incoming")]
    public partial class Grp_GreskeGreska
    {
        
        private string sifraGreskeField;
        
        private string nazivGreskeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string SifraGreske
        {
            get
            {
                return this.sifraGreskeField;
            }
            set
            {
                this.sifraGreskeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string NazivGreske
        {
            get
            {
                return this.nazivGreskeField;
            }
            set
            {
                this.nazivGreskeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SlanjeRezultataRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cezih.hr/HrVozacke/Incoming", Order=0)]
        public HRVozaci.PrijavaRezultata PrijavaRezultata;
        
        public SlanjeRezultataRequest()
        {
        }
        
        public SlanjeRezultataRequest(HRVozaci.PrijavaRezultata PrijavaRezultata)
        {
            this.PrijavaRezultata = PrijavaRezultata;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SlanjeRezultataResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.cezih.hr/HrVozacke/Incoming", Order=0)]
        public HRVozaci.PrijavaRezultataOdgovor PrijavaRezultataOdgovor;
        
        public SlanjeRezultataResponse()
        {
        }
        
        public SlanjeRezultataResponse(HRVozaci.PrijavaRezultataOdgovor PrijavaRezultataOdgovor)
        {
            this.PrijavaRezultataOdgovor = PrijavaRezultataOdgovor;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface RezultatiPortTypeChannel : HRVozaci.RezultatiPortType, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class RezultatiPortTypeClient : System.ServiceModel.ClientBase<HRVozaci.RezultatiPortType>, HRVozaci.RezultatiPortType
    {
        
        public RezultatiPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public HRVozaci.SlanjeRezultataResponse SlanjeRezultata(HRVozaci.SlanjeRezultataRequest request)
        {
            return base.Channel.SlanjeRezultata(request);
        }
        
        public System.Threading.Tasks.Task<HRVozaci.SlanjeRezultataResponse> SlanjeRezultataAsync(HRVozaci.SlanjeRezultataRequest request)
        {
            return base.Channel.SlanjeRezultataAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
    }
}
