//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=4.8.3928.0.
// 


namespace CezihECDSa.Wsdl.InfoOthers
{

    /// <remarks/>
    // CODEGEN: The optional WSDL extension element 'PolicyReference' from namespace 'http://schemas.xmlsoap.org/ws/2004/09/policy' was not handled.
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "BasicHttpBinding_IInfoOthers", Namespace = "http://tempuri.org/")]
    public partial class InfoOthers : System.Web.Services.Protocols.SoapHttpClientProtocol
    {

        private System.Threading.SendOrPostCallback DohvatiOthersOperationCompleted;

        private System.Threading.SendOrPostCallback DohvatiOthersNaDanOperationCompleted;

        private System.Threading.SendOrPostCallback AutorizacijaOthersOperationCompleted;

        private System.Threading.SendOrPostCallback AutorizacijaOthersPharmacyOperationCompleted;

        private System.Threading.SendOrPostCallback StornoOthersOperationCompleted;

        /// <remarks/>
        public InfoOthers()
        {
            this.Url = "https://hzzo-infoothers-test.gov.hr/InfoOthers/InfoOthers.svc";
        }

        /// <remarks/>
        public event DohvatiOthersCompletedEventHandler DohvatiOthersCompleted;

        /// <remarks/>
        public event DohvatiOthersNaDanCompletedEventHandler DohvatiOthersNaDanCompleted;

        /// <remarks/>
        public event AutorizacijaOthersCompletedEventHandler AutorizacijaOthersCompleted;

        /// <remarks/>
        public event AutorizacijaOthersPharmacyCompletedEventHandler AutorizacijaOthersPharmacyCompleted;

        /// <remarks/>
        public event StornoOthersCompletedEventHandler StornoOthersCompleted;

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IInfoOthers/DohvatiOthers", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public OsigStatus DohvatiOthers([System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string osiguravateljsifra, [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string pacijentoib)
        {
            object[] results = this.Invoke("DohvatiOthers", new object[] {
                    osiguravateljsifra,
                    pacijentoib});
            return ((OsigStatus)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginDohvatiOthers(string osiguravateljsifra, string pacijentoib, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("DohvatiOthers", new object[] {
                    osiguravateljsifra,
                    pacijentoib}, callback, asyncState);
        }

        /// <remarks/>
        public OsigStatus EndDohvatiOthers(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((OsigStatus)(results[0]));
        }

        /// <remarks/>
        public void DohvatiOthersAsync(string osiguravateljsifra, string pacijentoib)
        {
            this.DohvatiOthersAsync(osiguravateljsifra, pacijentoib, null);
        }

        /// <remarks/>
        public void DohvatiOthersAsync(string osiguravateljsifra, string pacijentoib, object userState)
        {
            if ((this.DohvatiOthersOperationCompleted == null))
            {
                this.DohvatiOthersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDohvatiOthersOperationCompleted);
            }
            this.InvokeAsync("DohvatiOthers", new object[] {
                    osiguravateljsifra,
                    pacijentoib}, this.DohvatiOthersOperationCompleted, userState);
        }

        private void OnDohvatiOthersOperationCompleted(object arg)
        {
            if ((this.DohvatiOthersCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DohvatiOthersCompleted(this, new DohvatiOthersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IInfoOthers/DohvatiOthersNaDan", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public OsigStatus DohvatiOthersNaDan([System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string osiguravateljsifra, [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string pacijentoib, System.DateTime dan, [System.Xml.Serialization.XmlIgnoreAttribute()] bool danSpecified)
        {
            object[] results = this.Invoke("DohvatiOthersNaDan", new object[] {
                    osiguravateljsifra,
                    pacijentoib,
                    dan,
                    danSpecified});
            return ((OsigStatus)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginDohvatiOthersNaDan(string osiguravateljsifra, string pacijentoib, System.DateTime dan, bool danSpecified, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("DohvatiOthersNaDan", new object[] {
                    osiguravateljsifra,
                    pacijentoib,
                    dan,
                    danSpecified}, callback, asyncState);
        }

        /// <remarks/>
        public OsigStatus EndDohvatiOthersNaDan(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((OsigStatus)(results[0]));
        }

        /// <remarks/>
        public void DohvatiOthersNaDanAsync(string osiguravateljsifra, string pacijentoib, System.DateTime dan, bool danSpecified)
        {
            this.DohvatiOthersNaDanAsync(osiguravateljsifra, pacijentoib, dan, danSpecified, null);
        }

        /// <remarks/>
        public void DohvatiOthersNaDanAsync(string osiguravateljsifra, string pacijentoib, System.DateTime dan, bool danSpecified, object userState)
        {
            if ((this.DohvatiOthersNaDanOperationCompleted == null))
            {
                this.DohvatiOthersNaDanOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDohvatiOthersNaDanOperationCompleted);
            }
            this.InvokeAsync("DohvatiOthersNaDan", new object[] {
                    osiguravateljsifra,
                    pacijentoib,
                    dan,
                    danSpecified}, this.DohvatiOthersNaDanOperationCompleted, userState);
        }

        private void OnDohvatiOthersNaDanOperationCompleted(object arg)
        {
            if ((this.DohvatiOthersNaDanCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DohvatiOthersNaDanCompleted(this, new DohvatiOthersNaDanCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IInfoOthers/AutorizacijaOthers", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public AutStatus AutorizacijaOthers([System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string osiguravateljsifra, [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string pacijentoib, [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string brojkartice, System.DateTime dattrosak, [System.Xml.Serialization.XmlIgnoreAttribute()] bool dattrosakSpecified, decimal transiznos, [System.Xml.Serialization.XmlIgnoreAttribute()] bool transiznosSpecified, short transtip, [System.Xml.Serialization.XmlIgnoreAttribute()] bool transtipSpecified, [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string ustanovasifra)
        {
            object[] results = this.Invoke("AutorizacijaOthers", new object[] {
                    osiguravateljsifra,
                    pacijentoib,
                    brojkartice,
                    dattrosak,
                    dattrosakSpecified,
                    transiznos,
                    transiznosSpecified,
                    transtip,
                    transtipSpecified,
                    ustanovasifra});
            return ((AutStatus)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginAutorizacijaOthers(string osiguravateljsifra, string pacijentoib, string brojkartice, System.DateTime dattrosak, bool dattrosakSpecified, decimal transiznos, bool transiznosSpecified, short transtip, bool transtipSpecified, string ustanovasifra, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("AutorizacijaOthers", new object[] {
                    osiguravateljsifra,
                    pacijentoib,
                    brojkartice,
                    dattrosak,
                    dattrosakSpecified,
                    transiznos,
                    transiznosSpecified,
                    transtip,
                    transtipSpecified,
                    ustanovasifra}, callback, asyncState);
        }

        /// <remarks/>
        public AutStatus EndAutorizacijaOthers(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((AutStatus)(results[0]));
        }

        /// <remarks/>
        public void AutorizacijaOthersAsync(string osiguravateljsifra, string pacijentoib, string brojkartice, System.DateTime dattrosak, bool dattrosakSpecified, decimal transiznos, bool transiznosSpecified, short transtip, bool transtipSpecified, string ustanovasifra)
        {
            this.AutorizacijaOthersAsync(osiguravateljsifra, pacijentoib, brojkartice, dattrosak, dattrosakSpecified, transiznos, transiznosSpecified, transtip, transtipSpecified, ustanovasifra, null);
        }

        /// <remarks/>
        public void AutorizacijaOthersAsync(string osiguravateljsifra, string pacijentoib, string brojkartice, System.DateTime dattrosak, bool dattrosakSpecified, decimal transiznos, bool transiznosSpecified, short transtip, bool transtipSpecified, string ustanovasifra, object userState)
        {
            if ((this.AutorizacijaOthersOperationCompleted == null))
            {
                this.AutorizacijaOthersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAutorizacijaOthersOperationCompleted);
            }
            this.InvokeAsync("AutorizacijaOthers", new object[] {
                    osiguravateljsifra,
                    pacijentoib,
                    brojkartice,
                    dattrosak,
                    dattrosakSpecified,
                    transiznos,
                    transiznosSpecified,
                    transtip,
                    transtipSpecified,
                    ustanovasifra}, this.AutorizacijaOthersOperationCompleted, userState);
        }

        private void OnAutorizacijaOthersOperationCompleted(object arg)
        {
            if ((this.AutorizacijaOthersCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AutorizacijaOthersCompleted(this, new AutorizacijaOthersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IInfoOthers/AutorizacijaOthersPharmacy", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public AutStatus AutorizacijaOthersPharmacy([System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string osiguravateljsifra, [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string pacijentoib, [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string brojkartice, System.DateTime dattrosak, [System.Xml.Serialization.XmlIgnoreAttribute()] bool dattrosakSpecified, decimal transiznos, [System.Xml.Serialization.XmlIgnoreAttribute()] bool transiznosSpecified, short transtip, [System.Xml.Serialization.XmlIgnoreAttribute()] bool transtipSpecified, [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string recsb, [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string erecid, [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string ustanovasifra)
        {
            object[] results = this.Invoke("AutorizacijaOthersPharmacy", new object[] {
                    osiguravateljsifra,
                    pacijentoib,
                    brojkartice,
                    dattrosak,
                    dattrosakSpecified,
                    transiznos,
                    transiznosSpecified,
                    transtip,
                    transtipSpecified,
                    recsb,
                    erecid,
                    ustanovasifra});
            return ((AutStatus)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginAutorizacijaOthersPharmacy(string osiguravateljsifra, string pacijentoib, string brojkartice, System.DateTime dattrosak, bool dattrosakSpecified, decimal transiznos, bool transiznosSpecified, short transtip, bool transtipSpecified, string recsb, string erecid, string ustanovasifra, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("AutorizacijaOthersPharmacy", new object[] {
                    osiguravateljsifra,
                    pacijentoib,
                    brojkartice,
                    dattrosak,
                    dattrosakSpecified,
                    transiznos,
                    transiznosSpecified,
                    transtip,
                    transtipSpecified,
                    recsb,
                    erecid,
                    ustanovasifra}, callback, asyncState);
        }

        /// <remarks/>
        public AutStatus EndAutorizacijaOthersPharmacy(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((AutStatus)(results[0]));
        }

        /// <remarks/>
        public void AutorizacijaOthersPharmacyAsync(string osiguravateljsifra, string pacijentoib, string brojkartice, System.DateTime dattrosak, bool dattrosakSpecified, decimal transiznos, bool transiznosSpecified, short transtip, bool transtipSpecified, string recsb, string erecid, string ustanovasifra)
        {
            this.AutorizacijaOthersPharmacyAsync(osiguravateljsifra, pacijentoib, brojkartice, dattrosak, dattrosakSpecified, transiznos, transiznosSpecified, transtip, transtipSpecified, recsb, erecid, ustanovasifra, null);
        }

        /// <remarks/>
        public void AutorizacijaOthersPharmacyAsync(string osiguravateljsifra, string pacijentoib, string brojkartice, System.DateTime dattrosak, bool dattrosakSpecified, decimal transiznos, bool transiznosSpecified, short transtip, bool transtipSpecified, string recsb, string erecid, string ustanovasifra, object userState)
        {
            if ((this.AutorizacijaOthersPharmacyOperationCompleted == null))
            {
                this.AutorizacijaOthersPharmacyOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAutorizacijaOthersPharmacyOperationCompleted);
            }
            this.InvokeAsync("AutorizacijaOthersPharmacy", new object[] {
                    osiguravateljsifra,
                    pacijentoib,
                    brojkartice,
                    dattrosak,
                    dattrosakSpecified,
                    transiznos,
                    transiznosSpecified,
                    transtip,
                    transtipSpecified,
                    recsb,
                    erecid,
                    ustanovasifra}, this.AutorizacijaOthersPharmacyOperationCompleted, userState);
        }

        private void OnAutorizacijaOthersPharmacyOperationCompleted(object arg)
        {
            if ((this.AutorizacijaOthersPharmacyCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AutorizacijaOthersPharmacyCompleted(this, new AutorizacijaOthersPharmacyCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IInfoOthers/StornoOthers", RequestNamespace = "http://tempuri.org/", ResponseNamespace = "http://tempuri.org/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public StornoStatus StornoOthers([System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string osiguravateljsifra, [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string pacijentoib, [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string brojkartice, System.DateTime dattrosak, [System.Xml.Serialization.XmlIgnoreAttribute()] bool dattrosakSpecified, decimal transiznos, [System.Xml.Serialization.XmlIgnoreAttribute()] bool transiznosSpecified, short transtip, [System.Xml.Serialization.XmlIgnoreAttribute()] bool transtipSpecified, [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)] string autkod)
        {
            object[] results = this.Invoke("StornoOthers", new object[] {
                    osiguravateljsifra,
                    pacijentoib,
                    brojkartice,
                    dattrosak,
                    dattrosakSpecified,
                    transiznos,
                    transiznosSpecified,
                    transtip,
                    transtipSpecified,
                    autkod});
            return ((StornoStatus)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginStornoOthers(string osiguravateljsifra, string pacijentoib, string brojkartice, System.DateTime dattrosak, bool dattrosakSpecified, decimal transiznos, bool transiznosSpecified, short transtip, bool transtipSpecified, string autkod, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("StornoOthers", new object[] {
                    osiguravateljsifra,
                    pacijentoib,
                    brojkartice,
                    dattrosak,
                    dattrosakSpecified,
                    transiznos,
                    transiznosSpecified,
                    transtip,
                    transtipSpecified,
                    autkod}, callback, asyncState);
        }

        /// <remarks/>
        public StornoStatus EndStornoOthers(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((StornoStatus)(results[0]));
        }

        /// <remarks/>
        public void StornoOthersAsync(string osiguravateljsifra, string pacijentoib, string brojkartice, System.DateTime dattrosak, bool dattrosakSpecified, decimal transiznos, bool transiznosSpecified, short transtip, bool transtipSpecified, string autkod)
        {
            this.StornoOthersAsync(osiguravateljsifra, pacijentoib, brojkartice, dattrosak, dattrosakSpecified, transiznos, transiznosSpecified, transtip, transtipSpecified, autkod, null);
        }

        /// <remarks/>
        public void StornoOthersAsync(string osiguravateljsifra, string pacijentoib, string brojkartice, System.DateTime dattrosak, bool dattrosakSpecified, decimal transiznos, bool transiznosSpecified, short transtip, bool transtipSpecified, string autkod, object userState)
        {
            if ((this.StornoOthersOperationCompleted == null))
            {
                this.StornoOthersOperationCompleted = new System.Threading.SendOrPostCallback(this.OnStornoOthersOperationCompleted);
            }
            this.InvokeAsync("StornoOthers", new object[] {
                    osiguravateljsifra,
                    pacijentoib,
                    brojkartice,
                    dattrosak,
                    dattrosakSpecified,
                    transiznos,
                    transiznosSpecified,
                    transtip,
                    transtipSpecified,
                    autkod}, this.StornoOthersOperationCompleted, userState);
        }

        private void OnStornoOthersOperationCompleted(object arg)
        {
            if ((this.StornoOthersCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.StornoOthersCompleted(this, new StornoOthersCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        public new void CancelAsync(object userState)
        {
            base.CancelAsync(userState);
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.datacontract.org/2004/07/SvcInfoOthers")]
    public partial class OsigStatus
    {

        private OsigPolica[] policeField;

        private bool statusField;

        private bool statusFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable = true)]
        public OsigPolica[] Police
        {
            get
            {
                return this.policeField;
            }
            set
            {
                this.policeField = value;
            }
        }

        /// <remarks/>
        public bool Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StatusSpecified
        {
            get
            {
                return this.statusFieldSpecified;
            }
            set
            {
                this.statusFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.datacontract.org/2004/07/SvcInfoOthers")]
    public partial class OsigPolica
    {

        private string brojKarticeField;

        private string tipPoliceField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string BrojKartice
        {
            get
            {
                return this.brojKarticeField;
            }
            set
            {
                this.brojKarticeField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string TipPolice
        {
            get
            {
                return this.tipPoliceField;
            }
            set
            {
                this.tipPoliceField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.datacontract.org/2004/07/SvcInfoOthers")]
    public partial class StornoStatus
    {

        private bool statusField;

        private bool statusFieldSpecified;

        /// <remarks/>
        public bool Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StatusSpecified
        {
            get
            {
                return this.statusFieldSpecified;
            }
            set
            {
                this.statusFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://schemas.datacontract.org/2004/07/SvcInfoOthers")]
    public partial class AutStatus
    {

        private string autKodField;

        private bool statusField;

        private bool statusFieldSpecified;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable = true)]
        public string AutKod
        {
            get
            {
                return this.autKodField;
            }
            set
            {
                this.autKodField = value;
            }
        }

        /// <remarks/>
        public bool Status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StatusSpecified
        {
            get
            {
                return this.statusFieldSpecified;
            }
            set
            {
                this.statusFieldSpecified = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    public delegate void DohvatiOthersCompletedEventHandler(object sender, DohvatiOthersCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DohvatiOthersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal DohvatiOthersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public OsigStatus Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((OsigStatus)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    public delegate void DohvatiOthersNaDanCompletedEventHandler(object sender, DohvatiOthersNaDanCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DohvatiOthersNaDanCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal DohvatiOthersNaDanCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public OsigStatus Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((OsigStatus)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    public delegate void AutorizacijaOthersCompletedEventHandler(object sender, AutorizacijaOthersCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AutorizacijaOthersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal AutorizacijaOthersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public AutStatus Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((AutStatus)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    public delegate void AutorizacijaOthersPharmacyCompletedEventHandler(object sender, AutorizacijaOthersPharmacyCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AutorizacijaOthersPharmacyCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal AutorizacijaOthersPharmacyCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public AutStatus Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((AutStatus)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    public delegate void StornoOthersCompletedEventHandler(object sender, StornoOthersCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class StornoOthersCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal StornoOthersCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
                base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public StornoStatus Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((StornoStatus)(this.results[0]));
            }
        }
    }
}