//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using CezihECDSa.Wsdl;

namespace CezihECDSa.Wsdl
{
    using System.Runtime.Serialization;
    using System;


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "MedicalOperater", Namespace = "http://schemas.datacontract.org/2004/07/NRS.Service")]
    [System.SerializableAttribute()]
    public partial class MedicalOperater : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InstitutionIdField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string InstitutionLocationField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MedicalActivityIdField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OperaterIDField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OperaterMBOField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OperaterTypeField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TeamIdField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InstitutionId
        {
            get
            {
                return this.InstitutionIdField;
            }
            set
            {
                this.InstitutionIdField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InstitutionLocation
        {
            get
            {
                return this.InstitutionLocationField;
            }
            set
            {
                this.InstitutionLocationField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MedicalActivityId
        {
            get
            {
                return this.MedicalActivityIdField;
            }
            set
            {
                this.MedicalActivityIdField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OperaterID
        {
            get
            {
                return this.OperaterIDField;
            }
            set
            {
                this.OperaterIDField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OperaterMBO
        {
            get
            {
                return this.OperaterMBOField;
            }
            set
            {
                this.OperaterMBOField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OperaterType
        {
            get
            {
                return this.OperaterTypeField;
            }
            set
            {
                this.OperaterTypeField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TeamId
        {
            get
            {
                return this.TeamIdField;
            }
            set
            {
                this.TeamIdField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "PatientReferenceData", Namespace = "http://schemas.datacontract.org/2004/07/NRS.Service")]
    [System.SerializableAttribute()]
    public partial class PatientReferenceData : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ActivityField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AlcoholismField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BMIField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FinalScreening_Q1Field;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FinalScreening_Q2Field;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int FinalScreening_Q3Field;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GenderField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int HeightField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool InitialScreening_Q1Field;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool InitialScreening_Q2Field;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool InitialScreening_Q3Field;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool InitialScreening_Q4Field;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MBOField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MainDiagnosisIdField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int MobilityStatusField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PlaceOfResidenceField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PsychoStatusField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] SecondaryDiagnosisListField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SmokingField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UpperArmScaleField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int WeightField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int WeightLossField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string YearOfBirthField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Activity
        {
            get
            {
                return this.ActivityField;
            }
            set
            {
                this.ActivityField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Alcoholism
        {
            get
            {
                return this.AlcoholismField;
            }
            set
            {
                this.AlcoholismField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BMI
        {
            get
            {
                return this.BMIField;
            }
            set
            {
                this.BMIField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FinalScreening_Q1
        {
            get
            {
                return this.FinalScreening_Q1Field;
            }
            set
            {
                this.FinalScreening_Q1Field = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FinalScreening_Q2
        {
            get
            {
                return this.FinalScreening_Q2Field;
            }
            set
            {
                this.FinalScreening_Q2Field = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FinalScreening_Q3
        {
            get
            {
                return this.FinalScreening_Q3Field;
            }
            set
            {
                this.FinalScreening_Q3Field = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Gender
        {
            get
            {
                return this.GenderField;
            }
            set
            {
                this.GenderField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Height
        {
            get
            {
                return this.HeightField;
            }
            set
            {
                this.HeightField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool InitialScreening_Q1
        {
            get
            {
                return this.InitialScreening_Q1Field;
            }
            set
            {
                this.InitialScreening_Q1Field = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool InitialScreening_Q2
        {
            get
            {
                return this.InitialScreening_Q2Field;
            }
            set
            {
                this.InitialScreening_Q2Field = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool InitialScreening_Q3
        {
            get
            {
                return this.InitialScreening_Q3Field;
            }
            set
            {
                this.InitialScreening_Q3Field = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool InitialScreening_Q4
        {
            get
            {
                return this.InitialScreening_Q4Field;
            }
            set
            {
                this.InitialScreening_Q4Field = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MBO
        {
            get
            {
                return this.MBOField;
            }
            set
            {
                this.MBOField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MainDiagnosisId
        {
            get
            {
                return this.MainDiagnosisIdField;
            }
            set
            {
                this.MainDiagnosisIdField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MobilityStatus
        {
            get
            {
                return this.MobilityStatusField;
            }
            set
            {
                this.MobilityStatusField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PlaceOfResidence
        {
            get
            {
                return this.PlaceOfResidenceField;
            }
            set
            {
                this.PlaceOfResidenceField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PsychoStatus
        {
            get
            {
                return this.PsychoStatusField;
            }
            set
            {
                this.PsychoStatusField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] SecondaryDiagnosisList
        {
            get
            {
                return this.SecondaryDiagnosisListField;
            }
            set
            {
                this.SecondaryDiagnosisListField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Smoking
        {
            get
            {
                return this.SmokingField;
            }
            set
            {
                this.SmokingField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UpperArmScale
        {
            get
            {
                return this.UpperArmScaleField;
            }
            set
            {
                this.UpperArmScaleField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Weight
        {
            get
            {
                return this.WeightField;
            }
            set
            {
                this.WeightField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int WeightLoss
        {
            get
            {
                return this.WeightLossField;
            }
            set
            {
                this.WeightLossField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string YearOfBirth
        {
            get
            {
                return this.YearOfBirthField;
            }
            set
            {
                this.YearOfBirthField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "ReferenceScoreResult", Namespace = "http://schemas.datacontract.org/2004/07/NRS.Service")]
    [System.SerializableAttribute()]
    public partial class ReferenceScoreResult : object, System.Runtime.Serialization.IExtensibleDataObject
    {

        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DateField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EntitetIdField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorDetailsField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ScoreField;

        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ScreenPerformedField;

        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Date
        {
            get
            {
                return this.DateField;
            }
            set
            {
                this.DateField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EntitetId
        {
            get
            {
                return this.EntitetIdField;
            }
            set
            {
                this.EntitetIdField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorDetails
        {
            get
            {
                return this.ErrorDetailsField;
            }
            set
            {
                this.ErrorDetailsField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Score
        {
            get
            {
                return this.ScoreField;
            }
            set
            {
                this.ScoreField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ScreenPerformed
        {
            get
            {
                return this.ScreenPerformedField;
            }
            set
            {
                this.ScreenPerformedField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName = "INutritionalReferenceScore")]
public interface INutritionalReferenceScore
{

    // CODEGEN: Generating message contract since the wrapper name (ReferenceScoreData) of message ReferenceScoreData does not match the default value (CalculateScore)
    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/INutritionalReferenceScore/CalculateScore", ReplyAction = "http://tempuri.org/INutritionalReferenceScore/CalculateScoreResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(ReferenceScoreResult), Action = "http://tempuri.org/INutritionalReferenceScore/CalculateScoreReferenceScoreResultF" +
        "ault", Name = "ReferenceScoreResult", Namespace = "http://schemas.datacontract.org/2004/07/NRS.Service")]
    ReferenceScoreResult CalculateScore(ReferenceScoreData request);

    [System.ServiceModel.OperationContractAttribute(AsyncPattern = true, Action = "http://tempuri.org/INutritionalReferenceScore/CalculateScore", ReplyAction = "http://tempuri.org/INutritionalReferenceScore/CalculateScoreResponse")]
    System.IAsyncResult BeginCalculateScore(ReferenceScoreData request, System.AsyncCallback callback, object asyncState);

    ReferenceScoreResult EndCalculateScore(System.IAsyncResult result);

    [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/INutritionalReferenceScore/CheckScreeningTimeSpanForMBO", ReplyAction = "http://tempuri.org/INutritionalReferenceScore/CheckScreeningTimeSpanForMBORespons" +
        "e")]
    string CheckScreeningTimeSpanForMBO(string MBO);

    [System.ServiceModel.OperationContractAttribute(AsyncPattern = true, Action = "http://tempuri.org/INutritionalReferenceScore/CheckScreeningTimeSpanForMBO", ReplyAction = "http://tempuri.org/INutritionalReferenceScore/CheckScreeningTimeSpanForMBORespons" +
        "e")]
    System.IAsyncResult BeginCheckScreeningTimeSpanForMBO(string MBO, System.AsyncCallback callback, object asyncState);

    string EndCheckScreeningTimeSpanForMBO(System.IAsyncResult result);
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName = "ReferenceScoreData", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
public partial class ReferenceScoreData
{

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
    public MedicalOperater MedicalOperater;

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 1)]
    public PatientReferenceData PatientReferenceData;

    public ReferenceScoreData()
    {
    }

    public ReferenceScoreData(MedicalOperater MedicalOperater, PatientReferenceData PatientReferenceData)
    {
        this.MedicalOperater = MedicalOperater;
        this.PatientReferenceData = PatientReferenceData;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName = "ReferenceScoreResult", WrapperNamespace = "http://tempuri.org/", IsWrapped = true)]
public partial class ReferenceScoreResult
{

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 0)]
    public string Date;

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 1)]
    public string EntitetId;

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 2)]
    public string ErrorDetails;

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 3)]
    public string Message;

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 4)]
    public int Score;

    [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://tempuri.org/", Order = 5)]
    public bool ScreenPerformed;

    public ReferenceScoreResult()
    {
    }

    public ReferenceScoreResult(string Date, string EntitetId, string ErrorDetails, string Message, int Score, bool ScreenPerformed)
    {
        this.Date = Date;
        this.EntitetId = EntitetId;
        this.ErrorDetails = ErrorDetails;
        this.Message = Message;
        this.Score = Score;
        this.ScreenPerformed = ScreenPerformed;
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface INutritionalReferenceScoreChannel : INutritionalReferenceScore, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class CalculateScoreCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{

    private object[] results;

    public CalculateScoreCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
        base(exception, cancelled, userState)
    {
        this.results = results;
    }

    public string EntitetId
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }

    public string ErrorDetails
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((string)(this.results[1]));
        }
    }

    public string Message
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((string)(this.results[2]));
        }
    }

    public int Score
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((int)(this.results[3]));
        }
    }

    public bool ScreenPerformed
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((bool)(this.results[4]));
        }
    }

    public string Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((string)(this.results[5]));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class CheckScreeningTimeSpanForMBOCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
{

    private object[] results;

    public CheckScreeningTimeSpanForMBOCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
        base(exception, cancelled, userState)
    {
        this.results = results;
    }

    public string Result
    {
        get
        {
            base.RaiseExceptionIfNecessary();
            return ((string)(this.results[0]));
        }
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class NutritionalReferenceScoreClient : System.ServiceModel.ClientBase<INutritionalReferenceScore>, INutritionalReferenceScore
{

    private BeginOperationDelegate onBeginCalculateScoreDelegate;

    private EndOperationDelegate onEndCalculateScoreDelegate;

    private System.Threading.SendOrPostCallback onCalculateScoreCompletedDelegate;

    private BeginOperationDelegate onBeginCheckScreeningTimeSpanForMBODelegate;

    private EndOperationDelegate onEndCheckScreeningTimeSpanForMBODelegate;

    private System.Threading.SendOrPostCallback onCheckScreeningTimeSpanForMBOCompletedDelegate;

    public NutritionalReferenceScoreClient()
    {
    }

    public NutritionalReferenceScoreClient(string endpointConfigurationName) :
        base(endpointConfigurationName)
    {
    }

    public NutritionalReferenceScoreClient(string endpointConfigurationName, string remoteAddress) :
        base(endpointConfigurationName, remoteAddress)
    {
    }

    public NutritionalReferenceScoreClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
        base(endpointConfigurationName, remoteAddress)
    {
    }

    public NutritionalReferenceScoreClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
        base(binding, remoteAddress)
    {
    }

    public event System.EventHandler<CalculateScoreCompletedEventArgs> CalculateScoreCompleted;

    public event System.EventHandler<CheckScreeningTimeSpanForMBOCompletedEventArgs> CheckScreeningTimeSpanForMBOCompleted;

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    ReferenceScoreResult INutritionalReferenceScore.CalculateScore(ReferenceScoreData request)
    {
        return base.Channel.CalculateScore(request);
    }

    public string CalculateScore(MedicalOperater MedicalOperater, PatientReferenceData PatientReferenceData, out string EntitetId, out string ErrorDetails, out string Message, out int Score, out bool ScreenPerformed)
    {
        ReferenceScoreData inValue = new ReferenceScoreData();
        inValue.MedicalOperater = MedicalOperater;
        inValue.PatientReferenceData = PatientReferenceData;
        ReferenceScoreResult retVal = ((INutritionalReferenceScore)(this)).CalculateScore(inValue);
        EntitetId = retVal.EntitetId;
        ErrorDetails = retVal.ErrorDetails;
        Message = retVal.Message;
        Score = retVal.Score;
        ScreenPerformed = retVal.ScreenPerformed;
        return retVal.Date;
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.IAsyncResult INutritionalReferenceScore.BeginCalculateScore(ReferenceScoreData request, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginCalculateScore(request, callback, asyncState);
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    public System.IAsyncResult BeginCalculateScore(MedicalOperater MedicalOperater, PatientReferenceData PatientReferenceData, System.AsyncCallback callback, object asyncState)
    {
        ReferenceScoreData inValue = new ReferenceScoreData();
        inValue.MedicalOperater = MedicalOperater;
        inValue.PatientReferenceData = PatientReferenceData;
        return ((INutritionalReferenceScore)(this)).BeginCalculateScore(inValue, callback, asyncState);
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    ReferenceScoreResult INutritionalReferenceScore.EndCalculateScore(System.IAsyncResult result)
    {
        return base.Channel.EndCalculateScore(result);
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    public string EndCalculateScore(System.IAsyncResult result, out string EntitetId, out string ErrorDetails, out string Message, out int Score, out bool ScreenPerformed)
    {
        ReferenceScoreResult retVal = ((INutritionalReferenceScore)(this)).EndCalculateScore(result);
        EntitetId = retVal.EntitetId;
        ErrorDetails = retVal.ErrorDetails;
        Message = retVal.Message;
        Score = retVal.Score;
        ScreenPerformed = retVal.ScreenPerformed;
        return retVal.Date;
    }

    private System.IAsyncResult OnBeginCalculateScore(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        MedicalOperater MedicalOperater = ((MedicalOperater)(inValues[0]));
        PatientReferenceData PatientReferenceData = ((PatientReferenceData)(inValues[1]));
        return this.BeginCalculateScore(MedicalOperater, PatientReferenceData, callback, asyncState);
    }

    private object[] OnEndCalculateScore(System.IAsyncResult result)
    {
        string EntitetId = this.GetDefaultValueForInitialization<string>();
        string ErrorDetails = this.GetDefaultValueForInitialization<string>();
        string Message = this.GetDefaultValueForInitialization<string>();
        int Score = this.GetDefaultValueForInitialization<int>();
        bool ScreenPerformed = this.GetDefaultValueForInitialization<bool>();
        string retVal = this.EndCalculateScore(result, out EntitetId, out ErrorDetails, out Message, out Score, out ScreenPerformed);
        return new object[] {
                EntitetId,
                ErrorDetails,
                Message,
                Score,
                ScreenPerformed,
                retVal};
    }

    private void OnCalculateScoreCompleted(object state)
    {
        if ((this.CalculateScoreCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.CalculateScoreCompleted(this, new CalculateScoreCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }

    public void CalculateScoreAsync(MedicalOperater MedicalOperater, PatientReferenceData PatientReferenceData)
    {
        this.CalculateScoreAsync(MedicalOperater, PatientReferenceData, null);
    }

    public void CalculateScoreAsync(MedicalOperater MedicalOperater, PatientReferenceData PatientReferenceData, object userState)
    {
        if ((this.onBeginCalculateScoreDelegate == null))
        {
            this.onBeginCalculateScoreDelegate = new BeginOperationDelegate(this.OnBeginCalculateScore);
        }
        if ((this.onEndCalculateScoreDelegate == null))
        {
            this.onEndCalculateScoreDelegate = new EndOperationDelegate(this.OnEndCalculateScore);
        }
        if ((this.onCalculateScoreCompletedDelegate == null))
        {
            this.onCalculateScoreCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCalculateScoreCompleted);
        }
        base.InvokeAsync(this.onBeginCalculateScoreDelegate, new object[] {
                    MedicalOperater,
                    PatientReferenceData}, this.onEndCalculateScoreDelegate, this.onCalculateScoreCompletedDelegate, userState);
    }

    public string CheckScreeningTimeSpanForMBO(string MBO)
    {
        return base.Channel.CheckScreeningTimeSpanForMBO(MBO);
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    public System.IAsyncResult BeginCheckScreeningTimeSpanForMBO(string MBO, System.AsyncCallback callback, object asyncState)
    {
        return base.Channel.BeginCheckScreeningTimeSpanForMBO(MBO, callback, asyncState);
    }

    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    public string EndCheckScreeningTimeSpanForMBO(System.IAsyncResult result)
    {
        return base.Channel.EndCheckScreeningTimeSpanForMBO(result);
    }

    private System.IAsyncResult OnBeginCheckScreeningTimeSpanForMBO(object[] inValues, System.AsyncCallback callback, object asyncState)
    {
        string MBO = ((string)(inValues[0]));
        return this.BeginCheckScreeningTimeSpanForMBO(MBO, callback, asyncState);
    }

    private object[] OnEndCheckScreeningTimeSpanForMBO(System.IAsyncResult result)
    {
        string retVal = this.EndCheckScreeningTimeSpanForMBO(result);
        return new object[] {
                retVal};
    }

    private void OnCheckScreeningTimeSpanForMBOCompleted(object state)
    {
        if ((this.CheckScreeningTimeSpanForMBOCompleted != null))
        {
            InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
            this.CheckScreeningTimeSpanForMBOCompleted(this, new CheckScreeningTimeSpanForMBOCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
        }
    }

    public void CheckScreeningTimeSpanForMBOAsync(string MBO)
    {
        this.CheckScreeningTimeSpanForMBOAsync(MBO, null);
    }

    public void CheckScreeningTimeSpanForMBOAsync(string MBO, object userState)
    {
        if ((this.onBeginCheckScreeningTimeSpanForMBODelegate == null))
        {
            this.onBeginCheckScreeningTimeSpanForMBODelegate = new BeginOperationDelegate(this.OnBeginCheckScreeningTimeSpanForMBO);
        }
        if ((this.onEndCheckScreeningTimeSpanForMBODelegate == null))
        {
            this.onEndCheckScreeningTimeSpanForMBODelegate = new EndOperationDelegate(this.OnEndCheckScreeningTimeSpanForMBO);
        }
        if ((this.onCheckScreeningTimeSpanForMBOCompletedDelegate == null))
        {
            this.onCheckScreeningTimeSpanForMBOCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCheckScreeningTimeSpanForMBOCompleted);
        }
        base.InvokeAsync(this.onBeginCheckScreeningTimeSpanForMBODelegate, new object[] {
                    MBO}, this.onEndCheckScreeningTimeSpanForMBODelegate, this.onCheckScreeningTimeSpanForMBOCompletedDelegate, userState);
    }
}
