//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CezihECDSa.Wsdl.SkolskaMedicina
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "https://ws.cezih.hr:15443/skolska", ConfigurationName = "SkolskaMedicina.SkolskaWSSoap12")]
    public interface SkolskaWSSoap12
    {

        [System.ServiceModel.OperationContractAttribute(Action = "https://ws.cezih.hr:15443/skolska/ZaprimanjeIzvjestaja", ReplyAction = "*")]
        System.Threading.Tasks.Task<SkolskaMedicina.ZaprimanjeIzvjestajaResponse> ZaprimanjeIzvjestajaAsync(SkolskaMedicina.ZaprimanjeIzvjestajaRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "https://ws.cezih.hr:15443/skolska/StatusIzvjestaja", ReplyAction = "*")]
        System.Threading.Tasks.Task<SkolskaMedicina.StatusIzvjestajaResponse> StatusIzvjestajaAsync(SkolskaMedicina.StatusIzvjestajaRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "https://ws.cezih.hr:15443/skolska/PromjenaPostojecegIzvjestaja", ReplyAction = "*")]
        System.Threading.Tasks.Task<SkolskaMedicina.PromjenaPostojecegIzvjestajaResponse> PromjenaPostojecegIzvjestajaAsync(SkolskaMedicina.PromjenaPostojecegIzvjestajaRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "https://ws.cezih.hr:15443/skolska/PostojiLiNoviZadatak", ReplyAction = "*")]
        System.Threading.Tasks.Task<SkolskaMedicina.PostojiLiNoviZadatakResponse> PostojiLiNoviZadatakAsync(SkolskaMedicina.PostojiLiNoviZadatakRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "https://ws.cezih.hr:15443/skolska/StatusZadatka", ReplyAction = "*")]
        System.Threading.Tasks.Task<SkolskaMedicina.StatusZadatkaResponse> StatusZadatkaAsync(SkolskaMedicina.StatusZadatkaRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "https://ws.cezih.hr:15443/skolska/SkolskiObveznici", ReplyAction = "*")]
        System.Threading.Tasks.Task<SkolskaMedicina.SkolskiObvezniciResponse> SkolskiObvezniciAsync(SkolskaMedicina.SkolskiObvezniciRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "https://ws.cezih.hr:15443/skolska/PopisUcenikaPoSkolama", ReplyAction = "*")]
        System.Threading.Tasks.Task<SkolskaMedicina.PopisUcenikaPoSkolamaResponse> PopisUcenikaPoSkolamaAsync(SkolskaMedicina.PopisUcenikaPoSkolamaRequest request);
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class ZaprimanjeIzvjestajaRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "ZaprimanjeIzvjestaja", Namespace = "https://ws.cezih.hr:15443/skolska", Order = 0)]
        public SkolskaMedicina.ZaprimanjeIzvjestajaRequestBody Body;

        public ZaprimanjeIzvjestajaRequest()
        {
        }

        public ZaprimanjeIzvjestajaRequest(SkolskaMedicina.ZaprimanjeIzvjestajaRequestBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "https://ws.cezih.hr:15443/skolska")]
    public partial class ZaprimanjeIzvjestajaRequestBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(Order = 0)]
        public byte[] jsonZahtjev;

        public ZaprimanjeIzvjestajaRequestBody()
        {
        }

        public ZaprimanjeIzvjestajaRequestBody(byte[] jsonZahtjev)
        {
            this.jsonZahtjev = jsonZahtjev;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class ZaprimanjeIzvjestajaResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "ZaprimanjeIzvjestajaResponse", Namespace = "https://ws.cezih.hr:15443/skolska", Order = 0)]
        public SkolskaMedicina.ZaprimanjeIzvjestajaResponseBody Body;

        public ZaprimanjeIzvjestajaResponse()
        {
        }

        public ZaprimanjeIzvjestajaResponse(SkolskaMedicina.ZaprimanjeIzvjestajaResponseBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "https://ws.cezih.hr:15443/skolska")]
    public partial class ZaprimanjeIzvjestajaResponseBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public byte[] ZaprimanjeIzvjestajaResult;

        public ZaprimanjeIzvjestajaResponseBody()
        {
        }

        public ZaprimanjeIzvjestajaResponseBody(byte[] ZaprimanjeIzvjestajaResult)
        {
            this.ZaprimanjeIzvjestajaResult = ZaprimanjeIzvjestajaResult;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class StatusIzvjestajaRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "StatusIzvjestaja", Namespace = "https://ws.cezih.hr:15443/skolska", Order = 0)]
        public SkolskaMedicina.StatusIzvjestajaRequestBody Body;

        public StatusIzvjestajaRequest()
        {
        }

        public StatusIzvjestajaRequest(SkolskaMedicina.StatusIzvjestajaRequestBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "https://ws.cezih.hr:15443/skolska")]
    public partial class StatusIzvjestajaRequestBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(Order = 0)]
        public string id;

        public StatusIzvjestajaRequestBody()
        {
        }

        public StatusIzvjestajaRequestBody(string id)
        {
            this.id = id;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class StatusIzvjestajaResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "StatusIzvjestajaResponse", Namespace = "https://ws.cezih.hr:15443/skolska", Order = 0)]
        public SkolskaMedicina.StatusIzvjestajaResponseBody Body;

        public StatusIzvjestajaResponse()
        {
        }

        public StatusIzvjestajaResponse(SkolskaMedicina.StatusIzvjestajaResponseBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "https://ws.cezih.hr:15443/skolska")]
    public partial class StatusIzvjestajaResponseBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public byte[] StatusIzvjestajaResult;

        public StatusIzvjestajaResponseBody()
        {
        }

        public StatusIzvjestajaResponseBody(byte[] StatusIzvjestajaResult)
        {
            this.StatusIzvjestajaResult = StatusIzvjestajaResult;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class PromjenaPostojecegIzvjestajaRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "PromjenaPostojecegIzvjestaja", Namespace = "https://ws.cezih.hr:15443/skolska", Order = 0)]
        public SkolskaMedicina.PromjenaPostojecegIzvjestajaRequestBody Body;

        public PromjenaPostojecegIzvjestajaRequest()
        {
        }

        public PromjenaPostojecegIzvjestajaRequest(SkolskaMedicina.PromjenaPostojecegIzvjestajaRequestBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "https://ws.cezih.hr:15443/skolska")]
    public partial class PromjenaPostojecegIzvjestajaRequestBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(Order = 0)]
        public byte[] jsonZahtjev;

        public PromjenaPostojecegIzvjestajaRequestBody()
        {
        }

        public PromjenaPostojecegIzvjestajaRequestBody(byte[] jsonZahtjev)
        {
            this.jsonZahtjev = jsonZahtjev;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class PromjenaPostojecegIzvjestajaResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "PromjenaPostojecegIzvjestajaResponse", Namespace = "https://ws.cezih.hr:15443/skolska", Order = 0)]
        public SkolskaMedicina.PromjenaPostojecegIzvjestajaResponseBody Body;

        public PromjenaPostojecegIzvjestajaResponse()
        {
        }

        public PromjenaPostojecegIzvjestajaResponse(SkolskaMedicina.PromjenaPostojecegIzvjestajaResponseBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "https://ws.cezih.hr:15443/skolska")]
    public partial class PromjenaPostojecegIzvjestajaResponseBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public byte[] PromjenaPostojecegIzvjestajaResult;

        public PromjenaPostojecegIzvjestajaResponseBody()
        {
        }

        public PromjenaPostojecegIzvjestajaResponseBody(byte[] PromjenaPostojecegIzvjestajaResult)
        {
            this.PromjenaPostojecegIzvjestajaResult = PromjenaPostojecegIzvjestajaResult;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class PostojiLiNoviZadatakRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "PostojiLiNoviZadatak", Namespace = "https://ws.cezih.hr:15443/skolska", Order = 0)]
        public SkolskaMedicina.PostojiLiNoviZadatakRequestBody Body;

        public PostojiLiNoviZadatakRequest()
        {
        }

        public PostojiLiNoviZadatakRequest(SkolskaMedicina.PostojiLiNoviZadatakRequestBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "https://ws.cezih.hr:15443/skolska")]
    public partial class PostojiLiNoviZadatakRequestBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(Order = 0)]
        public string sifraZavoda;

        [System.Runtime.Serialization.DataMemberAttribute(Order = 1)]
        public string HZJZSifraVoditelja;

        public PostojiLiNoviZadatakRequestBody()
        {
        }

        public PostojiLiNoviZadatakRequestBody(string sifraZavoda, string HZJZSifraVoditelja)
        {
            this.sifraZavoda = sifraZavoda;
            this.HZJZSifraVoditelja = HZJZSifraVoditelja;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class PostojiLiNoviZadatakResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "PostojiLiNoviZadatakResponse", Namespace = "https://ws.cezih.hr:15443/skolska", Order = 0)]
        public SkolskaMedicina.PostojiLiNoviZadatakResponseBody Body;

        public PostojiLiNoviZadatakResponse()
        {
        }

        public PostojiLiNoviZadatakResponse(SkolskaMedicina.PostojiLiNoviZadatakResponseBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "https://ws.cezih.hr:15443/skolska")]
    public partial class PostojiLiNoviZadatakResponseBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public byte[] PostojiLiNoviZadatakResult;

        public PostojiLiNoviZadatakResponseBody()
        {
        }

        public PostojiLiNoviZadatakResponseBody(byte[] PostojiLiNoviZadatakResult)
        {
            this.PostojiLiNoviZadatakResult = PostojiLiNoviZadatakResult;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class StatusZadatkaRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "StatusZadatka", Namespace = "https://ws.cezih.hr:15443/skolska", Order = 0)]
        public SkolskaMedicina.StatusZadatkaRequestBody Body;

        public StatusZadatkaRequest()
        {
        }

        public StatusZadatkaRequest(SkolskaMedicina.StatusZadatkaRequestBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "https://ws.cezih.hr:15443/skolska")]
    public partial class StatusZadatkaRequestBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(Order = 0)]
        public byte[] jsonZahtjev;

        public StatusZadatkaRequestBody()
        {
        }

        public StatusZadatkaRequestBody(byte[] jsonZahtjev)
        {
            this.jsonZahtjev = jsonZahtjev;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class StatusZadatkaResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "StatusZadatkaResponse", Namespace = "https://ws.cezih.hr:15443/skolska", Order = 0)]
        public SkolskaMedicina.StatusZadatkaResponseBody Body;

        public StatusZadatkaResponse()
        {
        }

        public StatusZadatkaResponse(SkolskaMedicina.StatusZadatkaResponseBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "https://ws.cezih.hr:15443/skolska")]
    public partial class StatusZadatkaResponseBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public byte[] StatusZadatkaResult;

        public StatusZadatkaResponseBody()
        {
        }

        public StatusZadatkaResponseBody(byte[] StatusZadatkaResult)
        {
            this.StatusZadatkaResult = StatusZadatkaResult;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class SkolskiObvezniciRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "SkolskiObveznici", Namespace = "https://ws.cezih.hr:15443/skolska", Order = 0)]
        public SkolskaMedicina.SkolskiObvezniciRequestBody Body;

        public SkolskiObvezniciRequest()
        {
        }

        public SkolskiObvezniciRequest(SkolskaMedicina.SkolskiObvezniciRequestBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "https://ws.cezih.hr:15443/skolska")]
    public partial class SkolskiObvezniciRequestBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(Order = 0)]
        public string zupanija;

        public SkolskiObvezniciRequestBody()
        {
        }

        public SkolskiObvezniciRequestBody(string zupanija)
        {
            this.zupanija = zupanija;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class SkolskiObvezniciResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "SkolskiObvezniciResponse", Namespace = "https://ws.cezih.hr:15443/skolska", Order = 0)]
        public SkolskaMedicina.SkolskiObvezniciResponseBody Body;

        public SkolskiObvezniciResponse()
        {
        }

        public SkolskiObvezniciResponse(SkolskaMedicina.SkolskiObvezniciResponseBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "https://ws.cezih.hr:15443/skolska")]
    public partial class SkolskiObvezniciResponseBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public byte[] SkolskiObvezniciResult;

        public SkolskiObvezniciResponseBody()
        {
        }

        public SkolskiObvezniciResponseBody(byte[] SkolskiObvezniciResult)
        {
            this.SkolskiObvezniciResult = SkolskiObvezniciResult;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class PopisUcenikaPoSkolamaRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "PopisUcenikaPoSkolama", Namespace = "https://ws.cezih.hr:15443/skolska", Order = 0)]
        public SkolskaMedicina.PopisUcenikaPoSkolamaRequestBody Body;

        public PopisUcenikaPoSkolamaRequest()
        {
        }

        public PopisUcenikaPoSkolamaRequest(SkolskaMedicina.PopisUcenikaPoSkolamaRequestBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "https://ws.cezih.hr:15443/skolska")]
    public partial class PopisUcenikaPoSkolamaRequestBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public string zupanija;

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 1)]
        public string OIB;

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 2)]
        public string maticnaSkola;

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 3)]
        public string podrucnaSkola;

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 4)]
        public string razred;

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 5)]
        public string odjeljenje;

        public PopisUcenikaPoSkolamaRequestBody()
        {
        }

        public PopisUcenikaPoSkolamaRequestBody(string zupanija, string OIB, string maticnaSkola, string podrucnaSkola, string razred, string odjeljenje)
        {
            this.zupanija = zupanija;
            this.OIB = OIB;
            this.maticnaSkola = maticnaSkola;
            this.podrucnaSkola = podrucnaSkola;
            this.razred = razred;
            this.odjeljenje = odjeljenje;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class PopisUcenikaPoSkolamaResponse
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Name = "PopisUcenikaPoSkolamaResponse", Namespace = "https://ws.cezih.hr:15443/skolska", Order = 0)]
        public SkolskaMedicina.PopisUcenikaPoSkolamaResponseBody Body;

        public PopisUcenikaPoSkolamaResponse()
        {
        }

        public PopisUcenikaPoSkolamaResponse(SkolskaMedicina.PopisUcenikaPoSkolamaResponseBody Body)
        {
            this.Body = Body;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace = "https://ws.cezih.hr:15443/skolska")]
    public partial class PopisUcenikaPoSkolamaResponseBody
    {

        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 0)]
        public byte[] PopisUcenikaPoSkolamaResult;

        public PopisUcenikaPoSkolamaResponseBody()
        {
        }

        public PopisUcenikaPoSkolamaResponseBody(byte[] PopisUcenikaPoSkolamaResult)
        {
            this.PopisUcenikaPoSkolamaResult = PopisUcenikaPoSkolamaResult;
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface SkolskaWSSoap12Channel : SkolskaMedicina.SkolskaWSSoap12, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class SkolskaWSSoap12Client : System.ServiceModel.ClientBase<SkolskaMedicina.SkolskaWSSoap12>, SkolskaMedicina.SkolskaWSSoap12
    {

        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);

        public SkolskaWSSoap12Client() :
                base(SkolskaWSSoap12Client.GetDefaultBinding(), SkolskaWSSoap12Client.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.SkolskaWSSoap12.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public SkolskaWSSoap12Client(EndpointConfiguration endpointConfiguration) :
                base(SkolskaWSSoap12Client.GetBindingForEndpoint(endpointConfiguration), SkolskaWSSoap12Client.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public SkolskaWSSoap12Client(EndpointConfiguration endpointConfiguration, string remoteAddress) :
                base(SkolskaWSSoap12Client.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public SkolskaWSSoap12Client(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) :
                base(SkolskaWSSoap12Client.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public SkolskaWSSoap12Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
                base(binding, remoteAddress)
        {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SkolskaMedicina.ZaprimanjeIzvjestajaResponse> SkolskaMedicina.SkolskaWSSoap12.ZaprimanjeIzvjestajaAsync(SkolskaMedicina.ZaprimanjeIzvjestajaRequest request)
        {
            return base.Channel.ZaprimanjeIzvjestajaAsync(request);
        }

        public System.Threading.Tasks.Task<SkolskaMedicina.ZaprimanjeIzvjestajaResponse> ZaprimanjeIzvjestajaAsync(byte[] jsonZahtjev)
        {
            SkolskaMedicina.ZaprimanjeIzvjestajaRequest inValue = new SkolskaMedicina.ZaprimanjeIzvjestajaRequest();
            inValue.Body = new SkolskaMedicina.ZaprimanjeIzvjestajaRequestBody();
            inValue.Body.jsonZahtjev = jsonZahtjev;
            return ((SkolskaMedicina.SkolskaWSSoap12)(this)).ZaprimanjeIzvjestajaAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SkolskaMedicina.StatusIzvjestajaResponse> SkolskaMedicina.SkolskaWSSoap12.StatusIzvjestajaAsync(SkolskaMedicina.StatusIzvjestajaRequest request)
        {
            return base.Channel.StatusIzvjestajaAsync(request);
        }

        public System.Threading.Tasks.Task<SkolskaMedicina.StatusIzvjestajaResponse> StatusIzvjestajaAsync(string id)
        {
            SkolskaMedicina.StatusIzvjestajaRequest inValue = new SkolskaMedicina.StatusIzvjestajaRequest();
            inValue.Body = new SkolskaMedicina.StatusIzvjestajaRequestBody();
            inValue.Body.id = id;
            return ((SkolskaMedicina.SkolskaWSSoap12)(this)).StatusIzvjestajaAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SkolskaMedicina.PromjenaPostojecegIzvjestajaResponse> SkolskaMedicina.SkolskaWSSoap12.PromjenaPostojecegIzvjestajaAsync(SkolskaMedicina.PromjenaPostojecegIzvjestajaRequest request)
        {
            return base.Channel.PromjenaPostojecegIzvjestajaAsync(request);
        }

        public System.Threading.Tasks.Task<SkolskaMedicina.PromjenaPostojecegIzvjestajaResponse> PromjenaPostojecegIzvjestajaAsync(byte[] jsonZahtjev)
        {
            SkolskaMedicina.PromjenaPostojecegIzvjestajaRequest inValue = new SkolskaMedicina.PromjenaPostojecegIzvjestajaRequest();
            inValue.Body = new SkolskaMedicina.PromjenaPostojecegIzvjestajaRequestBody();
            inValue.Body.jsonZahtjev = jsonZahtjev;
            return ((SkolskaMedicina.SkolskaWSSoap12)(this)).PromjenaPostojecegIzvjestajaAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SkolskaMedicina.PostojiLiNoviZadatakResponse> SkolskaMedicina.SkolskaWSSoap12.PostojiLiNoviZadatakAsync(SkolskaMedicina.PostojiLiNoviZadatakRequest request)
        {
            return base.Channel.PostojiLiNoviZadatakAsync(request);
        }

        public System.Threading.Tasks.Task<SkolskaMedicina.PostojiLiNoviZadatakResponse> PostojiLiNoviZadatakAsync(string sifraZavoda, string HZJZSifraVoditelja)
        {
            SkolskaMedicina.PostojiLiNoviZadatakRequest inValue = new SkolskaMedicina.PostojiLiNoviZadatakRequest();
            inValue.Body = new SkolskaMedicina.PostojiLiNoviZadatakRequestBody();
            inValue.Body.sifraZavoda = sifraZavoda;
            inValue.Body.HZJZSifraVoditelja = HZJZSifraVoditelja;
            return ((SkolskaMedicina.SkolskaWSSoap12)(this)).PostojiLiNoviZadatakAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SkolskaMedicina.StatusZadatkaResponse> SkolskaMedicina.SkolskaWSSoap12.StatusZadatkaAsync(SkolskaMedicina.StatusZadatkaRequest request)
        {
            return base.Channel.StatusZadatkaAsync(request);
        }

        public System.Threading.Tasks.Task<SkolskaMedicina.StatusZadatkaResponse> StatusZadatkaAsync(byte[] jsonZahtjev)
        {
            SkolskaMedicina.StatusZadatkaRequest inValue = new SkolskaMedicina.StatusZadatkaRequest();
            inValue.Body = new SkolskaMedicina.StatusZadatkaRequestBody();
            inValue.Body.jsonZahtjev = jsonZahtjev;
            return ((SkolskaMedicina.SkolskaWSSoap12)(this)).StatusZadatkaAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SkolskaMedicina.SkolskiObvezniciResponse> SkolskaMedicina.SkolskaWSSoap12.SkolskiObvezniciAsync(SkolskaMedicina.SkolskiObvezniciRequest request)
        {
            return base.Channel.SkolskiObvezniciAsync(request);
        }

        public System.Threading.Tasks.Task<SkolskaMedicina.SkolskiObvezniciResponse> SkolskiObvezniciAsync(string zupanija)
        {
            SkolskaMedicina.SkolskiObvezniciRequest inValue = new SkolskaMedicina.SkolskiObvezniciRequest();
            inValue.Body = new SkolskaMedicina.SkolskiObvezniciRequestBody();
            inValue.Body.zupanija = zupanija;
            return ((SkolskaMedicina.SkolskaWSSoap12)(this)).SkolskiObvezniciAsync(inValue);
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SkolskaMedicina.PopisUcenikaPoSkolamaResponse> SkolskaMedicina.SkolskaWSSoap12.PopisUcenikaPoSkolamaAsync(SkolskaMedicina.PopisUcenikaPoSkolamaRequest request)
        {
            return base.Channel.PopisUcenikaPoSkolamaAsync(request);
        }

        public System.Threading.Tasks.Task<SkolskaMedicina.PopisUcenikaPoSkolamaResponse> PopisUcenikaPoSkolamaAsync(string zupanija, string OIB, string maticnaSkola, string podrucnaSkola, string razred, string odjeljenje)
        {
            SkolskaMedicina.PopisUcenikaPoSkolamaRequest inValue = new SkolskaMedicina.PopisUcenikaPoSkolamaRequest();
            inValue.Body = new SkolskaMedicina.PopisUcenikaPoSkolamaRequestBody();
            inValue.Body.zupanija = zupanija;
            inValue.Body.OIB = OIB;
            inValue.Body.maticnaSkola = maticnaSkola;
            inValue.Body.podrucnaSkola = podrucnaSkola;
            inValue.Body.razred = razred;
            inValue.Body.odjeljenje = odjeljenje;
            return ((SkolskaMedicina.SkolskaWSSoap12)(this)).PopisUcenikaPoSkolamaAsync(inValue);
        }

        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }

        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SkolskaWSSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }

        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.SkolskaWSSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://localhost:44349/SkolskaWS.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }

        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return SkolskaWSSoap12Client.GetBindingForEndpoint(EndpointConfiguration.SkolskaWSSoap12);
        }

        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return SkolskaWSSoap12Client.GetEndpointAddress(EndpointConfiguration.SkolskaWSSoap12);
        }

        public enum EndpointConfiguration
        {

            SkolskaWSSoap12,
        }
    }
}

